"""Write the fixture the interface crate's tests read (crates/knos-oidc-interface/tests/fixtures): the bytes of a real
VERIFIED token account, and what a reader must find in them.

A GitHub-shaped token is signed with the seed-derived test key, written and verified by the test build of knos-oidc
in LiteSVM (tests/_settle.py), and the account is saved as it stands. Nothing is random (fixed payer, fixed clock,
and RSA PKCS#1 v1.5 signatures are deterministic), so the same bytes come out every time.

    python scripts/interface_fixture.py            # write verified_token.bin and verified_token.json
    python scripts/interface_fixture.py --check    # exit 1 if the committed fixture is not what this writes
"""
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tests"))

from solders.keypair import Keypair  # noqa: E402

from _settle import NOW, Chain, github_claims, modulus, sign_jwt, signing_key  # noqa: E402

from knos.settle import oidc  # noqa: E402

OUT = ROOT / "crates" / "knos-oidc-interface" / "tests" / "fixtures"
CLAIMS = github_claims(aud="oidc-gate:release", repository_id="424242001", sha="5" * 40,
                       job_workflow_ref="octo/widgets/.github/workflows/release.yml@refs/tags/v1.2.0")


def build() -> tuple[bytes, str]:
    c = Chain()
    payer = Keypair.from_seed(bytes([7]) * 32)
    c.svm.airdrop(payer.pubkey(), 10 ** 11)
    key = signing_key()
    assert c.register(oidc.GITHUB, modulus(key), payer=payer), c.err
    account = c.verify(sign_jwt(key, CLAIMS), oidc.GITHUB, modulus(key), payer=payer)
    assert account is not None, c.err
    data = c.data(account)
    tok = oidc.read_token(data)
    assert tok.verified and tok.claims() == CLAIMS
    want = {"note": "Generated by scripts/interface_fixture.py. Do not edit.", "owner": str(oidc.OIDC_ID), "account": str(account),
            "sha256": hashlib.sha256(data).hexdigest(), "now": NOW, "issuer": tok.issuer, "exp": tok.exp, "claims": CLAIMS}
    return data, json.dumps(want, indent=1) + "\n"


if __name__ == "__main__":
    data, text = build()
    b, j = OUT / "verified_token.bin", OUT / "verified_token.json"
    if "--check" in sys.argv:
        same = b.exists() and j.exists() and b.read_bytes() == data and j.read_text(encoding="utf-8") == text
        sys.exit(0 if same else "the interface crate's fixture is stale: run python scripts/interface_fixture.py")
    OUT.mkdir(parents=True, exist_ok=True)
    b.write_bytes(data)
    j.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {b} ({len(data)} bytes) and {j.name}")
