"""Write the fixtures the interface crate's tests read (crates/knos-oidc-interface/tests/fixtures): the bytes of a
real VERIFIED token account of each deployment, and what a reader must find in them.

A GitHub-shaped token is signed with the seed-derived test key, written and verified by the test build of knos-oidc
in LiteSVM (tests/_settle.py; tests/_oidc2.py for the second deployment), and the account is saved as it stands.
Nothing is random (fixed payer, fixed clock, and RSA PKCS#1 v1.5 signatures are deterministic), so the same bytes
come out every time. Both deployments get the same token from the same payer: the two accounts differ only in the
address of the key account, which is derived from the program's.

    python scripts/interface_fixture.py            # write verified_token{,_v2}.bin and verified_token{,_v2}.json
    python scripts/interface_fixture.py --check    # exit 1 if a committed fixture is not what this writes
"""
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tests"))

from solders.keypair import Keypair  # noqa: E402

from _settle import NOW, Chain, github_claims, modulus, sign_jwt, signing_key  # noqa: E402

from knos.settle import oidc  # noqa: E402

OUT = ROOT / "crates" / "knos-oidc-interface" / "tests" / "fixtures"
CLAIMS = github_claims(aud="oidc-gate:release", repository_id="424242001", sha="5" * 40,
                       job_workflow_ref="octo/widgets/.github/workflows/release.yml@refs/tags/v1.2.0")


def build(second: bool = False) -> tuple[bytes, str]:
    """The fixture of the first deployment, or of the second: (the account's bytes, the JSON beside them)."""
    if second:
        from _oidc2 import Chain2

        from knos.settle.v2 import oidc as client
        c = Chain2()
    else:
        c, client = Chain(), oidc
    payer = Keypair.from_seed(bytes([7]) * 32)
    c.svm.airdrop(payer.pubkey(), 10 ** 11)
    key = signing_key()
    assert c.register(client.GITHUB, modulus(key), payer=payer), c.err
    account = c.verify(sign_jwt(key, CLAIMS), client.GITHUB, modulus(key), payer=payer)
    assert account is not None, c.err
    data = c.data(account)
    tok = client.read_token(data)
    assert tok.verified and tok.claims() == CLAIMS
    want = {"note": "Generated by scripts/interface_fixture.py. Do not edit.", "owner": str(client.OIDC_ID), "account": str(account),
            "sha256": hashlib.sha256(data).hexdigest(), "now": NOW, "issuer": tok.issuer, "exp": tok.exp, "claims": CLAIMS}
    return data, json.dumps(want, indent=1) + "\n"


if __name__ == "__main__":
    stale = []
    for name, second in (("verified_token", False), ("verified_token_v2", True)):
        data, text = build(second)
        b, j = OUT / f"{name}.bin", OUT / f"{name}.json"
        if "--check" in sys.argv:
            if not (b.exists() and j.exists() and b.read_bytes() == data and j.read_text(encoding="utf-8") == text):
                stale.append(name)
            continue
        OUT.mkdir(parents=True, exist_ok=True)
        b.write_bytes(data)
        j.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {b} ({len(data)} bytes) and {j.name}")
    if stale:
        sys.exit(f"the interface crate's fixture is stale ({', '.join(stale)}): run python scripts/interface_fixture.py")
