"""Write the fixture the pay interface crate's tests read (crates/knos-pay-interface/tests/fixtures/pay_interface.json):
what the Python client (src/knos/settle/v2/pay.py) derives and builds for fixed inputs, and one Order account as the
test build of knos_pay wrote it in LiteSVM. The crate's tests rebuild every address and instruction from the same
inputs and must get the same bytes, so the two clients cannot drift apart.

Nothing is random: the funder and the mint come from seeds and the chain's clock is fixed, so the same file comes out
every time.

    python scripts/pay_interface_fixture.py            # write the fixture
    python scripts/pay_interface_fixture.py --check    # exit 1 if the committed fixture is not what this writes
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tests"))

from solders.keypair import Keypair  # noqa: E402
from solders.pubkey import Pubkey  # noqa: E402

from knos.settle.v2 import pay  # noqa: E402

OUT = ROOT / "crates" / "knos-pay-interface" / "tests" / "fixtures" / "pay_interface.json"
FUNDER = Keypair.from_seed(bytes([21]) * 32)
RELAYER = Keypair.from_seed(bytes([22]) * 32).pubkey()
REPO, ISSUE, AMOUNT, WORK, SEQ = 987654321, 77, 20_000_000, 7 * 86_400, 3
WF_REPO, WF_SHA = "drexthealpha/Knos", "c" * 40
TERMS = pay.terms_json({"accept": "", "checks": [{"app": 15368, "name": "test"}], "mode": "merge", "v": 2})
OPTS = dict(flags=pay.F_NEUTRAL, holdback_bps=1000, warranty_days=30, kill_bps=500, reserve_days=7, rate=0, arbiter_id=424242, judge_repo_id=0)
SALT = bytes(range(32))


def _ix(name: str, ix, **args) -> dict:
    return {"name": name, **args, "program": str(ix.program_id), "data": bytes(ix.data).hex(),
            "accounts": [[str(a.pubkey), a.is_signer, a.is_writable] for a in ix.accounts]}


def _order(o: pay.Order) -> dict:
    out = {}
    for k, v in vars(o).items():
        out[k] = v.hex() if isinstance(v, bytes) else str(v) if isinstance(v, Pubkey) else v
    return out


def build() -> str:
    from _pay2 import USDC_KEY, Chain
    c = Chain()
    f = FUNDER.pubkey()
    c.svm.airdrop(f, 10 ** 10)
    mint = c.new_mint(keypair=USDC_KEY)
    tok = c.token_account(f, mint)
    c.mint_to(mint, tok, 1_000 * 10 ** 6)
    options = pay.opts(**OPTS)
    fund = pay.fund_order_wallet_ix(f, tok, mint, REPO, ISSUE, AMOUNT, WF_REPO, WF_SHA, TERMS, pay.MERGE, WORK, SEQ, options)
    assert c.send([fund], FUNDER), c.err
    order = fund.accounts[1].pubkey
    data = c.data(order)
    o = pay.read_order(data)
    assert o is not None and (o.amount, o.fee, o.source, o.state) == (AMOUNT, pay.order_fee(AMOUNT), f, "open")
    assert c.balance(pay.ov_pda(order)) == AMOUNT + o.fee
    # a private order: its scope is the funder's, its repository and issue are not on chain, its terms are a hash
    scope = pay.scope_of(REPO, ISSUE, SALT)
    popts = pay.opts(flags=pay.F_PRIVATE, judge_repo_id=5150, salted=True)
    private = pay.fund_order_wallet_ix(f, tok, mint, 0, 0, AMOUNT, WF_REPO, WF_SHA, pay.terms_hash(TERMS), pay.TESTS, WORK, 0, popts, scope)
    want = {
        "note": "Generated by scripts/pay_interface_fixture.py. Do not edit.",
        "program": str(pay.PAY_ID), "fee_owner": str(pay.FEE_OWNER), "now": c.now(),
        "funder": str(f), "funder_token": str(tok), "relayer": str(RELAYER), "mint": str(mint),
        "repo_id": REPO, "issue": ISSUE, "amount": AMOUNT, "work_s": WORK, "seq": SEQ, "wf_repo": WF_REPO, "wf_sha": WF_SHA,
        "terms": TERMS.decode(), "terms_hash": pay.terms_hash(TERMS).hex(), "salt": SALT.hex(), "opts": OPTS, "opts_hex": options.hex(),
        "addresses": {"auth": str(pay.auth_pda()), "pause": str(pay.pause_pda()), "scope": pay.scope_of(REPO, ISSUE).hex(),
                      "private_scope": scope.hex(), "order": str(order), "ov": str(pay.ov_pda(order)), "ata": str(pay.ata(f, mint))},
        "fees": [[a, b, d, pay.order_fee(a, b, d)] for a, b, d in ((5_000_000, 250, 6), (16_000_040, 250, 6), (500_000_000, 250, 6),
                                                                  (2_000_000_000, 250, 6), (100_000_000, 50, 6), (5_000_000_000, 250, 9), (500, 250, 2),
                                                                  # the tier edges, a Plan's rate on the first tier, the cap, and past it
                                                                  (999_999_999, 250, 6), (1_000_000_000, 250, 6), (1_000_000_100, 250, 6),
                                                                  (49_999_999_999, 250, 6), (50_000_000_000, 250, 6), (50_000_000_200, 250, 6),
                                                                  (2_000_000_000, 50, 6), (pay.MAX_AMOUNT, 250, 6), (10 ** 15, 250, 9), (2 ** 64 - 1, 250, 6),
                                                                  (2 ** 64 - 1, 250, 18))],
        "order": {"address": str(order), "owner": str(pay.PAY_ID), "data": data.hex(), "fields": _order(o)},
        "instructions": [
            _ix("fund_order_wallet", fund),
            _ix("fund_order_wallet_private", private),
            _ix("top_up", pay.top_up_ix(f, order, o, 5_000_000), add=5_000_000),
            _ix("top_up_from", pay.top_up_ix(f, order, o, 1, RELAYER), add=1, token=str(RELAYER)),
            _ix("refund_order", pay.refund_order_ix(RELAYER, order, o)),
            _ix("refund_order_to", pay.refund_order_ix(RELAYER, order, o, tok), token=str(tok)),
        ],
    }
    return json.dumps(want, indent=1) + "\n"


if __name__ == "__main__":
    text = build()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            sys.exit("the pay interface crate's fixture is stale: run python scripts/pay_interface_fixture.py")
        sys.exit(0)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT}")
