"""Write sdk/settle/fixtures.json: knos-oidc, knos-pay and knos-meter addresses, audiences, instructions and accounts encoded by
the Python client (the authority, src/knos/settle), so any other client (the web app's JavaScript, an npm package, a
program doing CPI) can check its encodings byte for byte, offline.  Run: python scripts/settle_fixtures.py
`--check` exits 1 if the file on disk is stale.

The top level is the first deployment (programs/), as it always was. `second` is the second deployment
(programs-v2/, src/knos/settle/v2): the same kinds of entries, the accounts as bytes with what the readers make of
them, what `key_usable` says about a key, and each transaction the site asks a wallet to sign, as solders serialises it.
"""
import base64
import dataclasses
import json
import sys
from pathlib import Path

from solders.hash import Hash
from solders.instruction import AccountMeta, Instruction
from solders.message import Message
from solders.pubkey import Pubkey
from solders.transaction import Transaction

from solders.message import MessageV1, TransactionConfig, to_bytes_versioned

from knos import chain, fees
from knos.settle import oidc, pay
from knos.settle.v2 import meter
from knos.settle.v2 import oidc as oidc2
from knos.settle.v2 import passkey as passkey2
from knos.settle.v2 import passkey_fund
from knos.settle.v2 import pay as pay2

OUT = Path(__file__).resolve().parents[1] / "sdk" / "settle" / "fixtures.json"
NAMES = ["payer", "funder", "funder_token", "mint", "relayer", "address", "rent_to", "token_account"]
K = {n: Pubkey(bytes([i + 1]) * 32) for i, n in enumerate(NAMES)}
REPO, ISSUE, AUTHOR, OWNER, AMOUNT = 987654321, 7, 1234567, 424242, 5_000_000
N2048 = (1 << 2047) | 0x1234567  # an odd 2048-bit number: only its encoding matters here
CHECKS = bytes(range(32))
TID = bytes([0xC0 + i for i in range(32)])
JWT = "eyJhbGciOiJSUzI1NiJ9." + "A" * 1000 + ".c2ln"

# -- the second deployment's inputs ---------------------------------------------------------------------------------
NAMES2 = [*NAMES, "authority", "wallet", "dest_token", "mint22", "attest", "key"]
K2 = {n: Pubkey(bytes([i + 1]) * 32) for i, n in enumerate(NAMES2)}
N4096 = (1 << 4095) | 0x1234567
N2048_B = (1 << 2047) | 0x89ABCD3     # its low bits make -n^-1 mod 2^32 take every round of the iteration that finds it
MAINT, SPENDERS, CAP = 555000, [555000, 9], 20_000_000
T22 = pay2.TOKEN_2022
TERMS = {"accept": "", "checks": [{"app": 15368, "name": "test"}], "deny": [".github/**", ".knos/**"], "mode": "merge", "paths": [],
         "reserve": 7, "v": 1}
TERMS_TESTS = {**TERMS, "accept": "ab" * 32, "mode": "tests", "paths": ["src/**", "caf\u00e9/*.md", "docs/\U0001f4c4*"]}
ODD = {"z": ["tab\there", "del\x7f", "quote\"", "back\\slash", "line\u2028", "nul\x00", "slash/"], "a": {"b": 1, "a": [True, None, -2]}}
WF_REPO, WF_SHA, HEAD = "drexthealpha/knos-workflows", "c" * 40, "a" * 40
NOW = 1_790_000_000
BLOCKHASH = Hash(bytes([0xBB]) * 32)
TRANSFER_CHECKED = 12       # SPL Token and Token-2022: TransferChecked { amount u64, decimals u8 }


def ix(i) -> dict:
    return {"program": str(i.program_id), "data": bytes(i.data).hex(),
            "accounts": [{"pubkey": str(a.pubkey), "signer": a.is_signer, "writable": a.is_writable} for a in i.accounts]}


def build() -> dict:
    job_own, job_wallet = pay.job_pda(REPO, ISSUE), pay.job_pda(REPO, ISSUE, K["funder"])
    return {
        "note": "Generated by scripts/settle_fixtures.py from src/knos/settle. Do not edit.",
        "programs": {"knos_oidc": str(oidc.OIDC_ID), "knos_pay": str(pay.PAY_ID)},
        "inputs": {**{k: str(v) for k, v in K.items()}, "repo_id": REPO, "issue": ISSUE, "author_id": AUTHOR, "owner_id": OWNER,
                   "amount": AMOUNT, "checks": CHECKS.hex(), "token_id": TID.hex(), "n2048": hex(N2048), "jwt": JWT,
                   "wf_repo": "drexthealpha/Knos", "wf_sha": "c" * 40},
        "addresses": {
            "auth": str(pay.auth_pda()), "vault(mint)": str(pay.vault_pda(K["mint"])), "faucet_mint": str(pay.faucet_mint()),
            "job(repo, issue) own": str(job_own), "job(repo, issue, funder)": str(job_wallet),
            "due(author, mint)": str(pay.due_pda(AUTHOR, K["mint"])), "rep(author)": str(pay.rep_pda(AUTHOR)),
            "rate(repo)": str(pay.rate_pda(REPO)), "ata(address, mint)": str(pay.ata(K["address"], K["mint"])),
            "fee_account(mint)": str(pay.ata(pay.FEE_OWNER, K["mint"])),
            "token(payer, token_id)": str(oidc.token_pda(K["payer"], TID)), "key(github, n2048)": str(oidc.key_pda(oidc.GITHUB, N2048)),
        },
        "audiences": {
            "fund merge": pay.fund_audience(ISSUE, AMOUNT),
            "fund tests": pay.fund_audience(ISSUE, AMOUNT, pay.TESTS, CHECKS, 14 * 86_400, 86_400),
            "pay merge": pay.pay_audience(REPO, ISSUE, AUTHOR, "a" * 40),
            "pay tests": pay.pay_audience(REPO, ISSUE, AUTHOR, "a" * 40, CHECKS, pay.TESTS),
            "veto": pay.veto_audience(REPO, ISSUE), "claim": pay.claim_audience(K["address"]),
            "rotate": oidc.rotate_audience(oidc.GITHUB, N2048),
        },
        "wf_repo_hash": pay.wf_repo_hash("drexthealpha/Knos").hex(),
        "fees": {str(a): pay.fee_of(a) for a in (0, 1, 50_000, 1_000_000, 2_000_000, 5_000_000, 500_000_000)},
        "instructions": {
            "oidc.write (first chunk)": ix(oidc.write_ixs(K["payer"], TID, JWT)[0]),
            "oidc.write (last chunk)": ix(oidc.write_ixs(K["payer"], TID, JWT)[-1]),
            "oidc.step": ix(oidc.step_ix(K["payer"], TID, oidc.key_pda(oidc.GITHUB, N2048), 8)),
            "oidc.close": ix(oidc.close_ix(K["payer"], TID)),
            "oidc.register_key": ix(oidc.register_key_ix(K["payer"], oidc.GITHUB, N2048)),
            "oidc.register_key (attested)": ix(oidc.register_key_ix(K["payer"], oidc.GITHUB, N2048, K["token_account"])),
            "oidc.key_params": ix(oidc.key_params_ix(K["payer"], oidc.GITHUB, N2048)),
            "pay.fund merge": ix(pay.fund_ix(K["funder"], K["funder_token"], K["mint"], REPO, ISSUE, AMOUNT, "drexthealpha/Knos", "c" * 40)),
            "pay.fund tests": ix(pay.fund_ix(K["funder"], K["funder_token"], K["mint"], REPO, ISSUE, AMOUNT, "drexthealpha/Knos", "c" * 40,
                                             mode=pay.TESTS, checks=CHECKS, work_s=7 * 86_400, review_s=86_400)),
            "pay.fund_with_token": ix(pay.fund_with_token_ix(K["relayer"], K["token_account"], REPO, ISSUE)),
            "pay.pay": ix(pay.pay_ix(K["relayer"], K["token_account"], job_wallet, AUTHOR, K["mint"], K["funder"])),
            "pay.settle": ix(pay.settle_ix(K["relayer"], job_wallet, AUTHOR, K["mint"], K["funder"])),
            "pay.veto (wallet)": ix(pay.veto_ix(K["funder"], job_wallet)),
            "pay.veto (token)": ix(pay.veto_ix(K["relayer"], job_own, K["token_account"])),
            "pay.refund": ix(pay.refund_ix(K["relayer"], job_wallet, K["mint"], K["funder_token"], K["funder"])),
            "pay.claim": ix(pay.claim_ix(K["relayer"], K["token_account"], AUTHOR, K["mint"], K["address"])),
            "pay.init_faucet": ix(pay.init_faucet_ix(K["payer"])),
            "create_ata": ix(pay.create_ata_ix(K["relayer"], K["address"], K["mint"])),
        },
        "layouts": {
            "job (256 bytes)": "0 state u8 (1 open, 2 proven) | 1 mode u8 | 2 kind u8 (0 wallet, 1 GitHub) | 8 repo_id u64 | 16 issue u64 | 24 amount u64 | "
                               "32 deadline i64 | 40 review i64 | 48 pay_after i64 | 56 author_id u64 | 64 funder_id u64 | 72 not_before i64 | 80 vetoes u32 | "
                               "88 funder[32] | 120 mint[32] | 152 checks[32] | 184 wf_repo_hash[32] | 216 wf_sha[40]",
            "due (48 bytes)": "0 amount u64 | 8 github user id u64 | 16 mint[32]",
            "rep (32 bytes)": "0 paid jobs u32 | 8 total paid u64 | 16 distinct repositories u32 | 24 last repository u64",
            "token (626 + jwt bytes)": "0 stage u8 (2 = verified) | 1 issuer u8 | 2 squarings done u8 | 3 limbs u8 | 4 jwt_len u16 | 6 payload_off u16 | "
                                       "8 payload_len u16 | 10 exp i64 | 18 key[32] | 50 payer[32] | 82 id[32] | 114 x[512] | 626 jwt",
            "key (8 + 8 * limbs bytes)": "0 ready u8 | 1 issuer u8 | 2 limbs u8 (64 or 128) | 3 bump u8 | 4 n0inv u32 | 8 n (LE limbs) | then r2 (LE limbs)",
        },
        "second": second(),
    }


# -- the second deployment ------------------------------------------------------------------------------------------
def _put(buf: bytearray, at: int, value, size: int = 8, signed: bool = False) -> None:
    raw = value.to_bytes(size, "little", signed=signed) if isinstance(value, int) else bytes(value)
    buf[at:at + len(raw)] = raw


def job_bytes(*, state=1, mode=0, kind=1, token_program=0, faucet=0, repo=REPO, issue=ISSUE, amount=AMOUNT, deadline=NOW + 14 * 86_400,
              hold_until=0, payee=0, funder_id=MAINT, not_before=NOW, owner_id=OWNER, source, refund_to, rent_to, mint, terms, wf_repo, wf_sha) -> bytes:
    """A job account, laid out as programs-v2/knos_pay/src/state.rs lays it out (idl/knos_pay_v2.json, Job)."""
    d = bytearray(pay2.JOB_LEN)
    d[0], d[1], d[2], d[3], d[6], d[7] = state, mode, kind, 254, token_program, faucet
    for at, v, signed in ((8, repo, False), (16, issue, False), (24, amount, False), (32, deadline, True), (48, hold_until, True),
                          (56, payee, False), (64, funder_id, False), (72, not_before, True), (80, owner_id, False)):
        _put(d, at, v, signed=signed)
    for at, v in ((88, source), (120, refund_to), (152, rent_to), (184, mint), (216, terms), (248, pay2.wf_repo_hash(wf_repo)), (280, wf_sha.encode())):
        _put(d, at, v)
    return bytes(d)


def balance_bytes(*, faucet=0, owner_id=OWNER, authority, mint, cap=CAP, last_iat=NOW - 60, spenders=SPENDERS, spent=7_500_000, has_x=0) -> bytes:
    d = bytearray(pay2.BALANCE_LEN)
    d[0], d[1], d[2], d[3] = 1, 253, faucet, has_x
    _put(d, 8, owner_id); _put(d, 16, authority); _put(d, 48, mint); _put(d, 80, cap); _put(d, 88, last_iat, signed=True)
    for i, s in enumerate(spenders):
        _put(d, 96 + 8 * i, s)
    _put(d, 128, spent)
    return bytes(d)


def bind_bytes(user: int, wallet: Pubkey, iat: int) -> bytes:
    d = bytearray(pay2.BIND_LEN)
    d[0], d[1] = 1, 255
    _put(d, 8, user); _put(d, 16, wallet); _put(d, 48, iat, signed=True)
    return bytes(d)


def rep_bytes(paid=3, funders=2, total=58_500_000, test_paid=4, self_paid=1, test_total=19_500_000, first=NOW - 86_400, last=NOW) -> bytes:
    d = bytearray(pay2.REP_LEN)
    _put(d, 0, paid, 4); _put(d, 4, funders, 4); _put(d, 8, total); _put(d, 16, test_paid, 4); _put(d, 20, self_paid, 4)
    _put(d, 32, test_total); _put(d, 40, first, signed=True); _put(d, 48, last, signed=True)
    return bytes(d)


def order_bytes(*, state=1, mode=0, kind=1, flags=pay2.F_NEUTRAL, decimals=6, reserve_days=7, repo=REPO, issue=ISSUE, scope, seq=0, holdback_bps=0, kill_bps=0,
                amount=AMOUNT, fee=400_000, rate=0, paid=0, deadline=NOW + 14 * 86_400, not_before=NOW, hold_until=0, warranty_s=0, reserved_by=0,
                reserved_until=0, cancel_at=0, payee=0, funder_id=MAINT, owner_id=OWNER, arbiter_id=0, judge_repo_id=0, source, refund_to, rent_to, mint,
                terms, wf_repo=WF_REPO, wf_sha=WF_SHA, fee_bps=250) -> bytes:
    """An order account, laid out as programs-v2/knos_pay/src/state.rs lays it out (the offsets are read_order's)."""
    d = bytearray(pay2.ORDER_LEN)
    d[0], d[1], d[2], d[3], d[4], d[5], d[6], d[7] = 2, state, mode, kind, flags, 251, decimals, reserve_days
    for at, v, size, signed in ((8, repo, 8, False), (16, issue, 8, False), (56, seq, 4, False), (60, holdback_bps, 2, False), (62, kill_bps, 2, False),
                                (64, amount, 8, False), (72, fee, 8, False), (80, rate, 8, False), (88, paid, 8, False), (96, deadline, 8, True),
                                (104, not_before, 8, True), (112, hold_until, 8, True), (120, warranty_s, 8, True), (128, reserved_by, 8, False),
                                (136, reserved_until, 8, True), (144, cancel_at, 8, True), (152, payee, 8, False), (160, funder_id, 8, False),
                                (168, owner_id, 8, False), (176, arbiter_id, 8, False), (184, judge_repo_id, 8, False), (424, fee_bps, 2, False)):
        _put(d, at, v, size, signed)
    for at, v in ((24, scope), (192, source), (224, refund_to), (256, rent_to), (288, mint), (320, terms), (352, pay2.wf_repo_hash(wf_repo)), (384, wf_sha.encode())):
        _put(d, at, v)
    return bytes(d)


def balx_bytes(*, day_limit=50_000_000, total_limit=500_000_000, repos=(REPO, 7), wf_sha=WF_SHA, day=NOW // 86_400, day_spent=12_000_000, total_spent=40_000_000) -> bytes:
    d = bytearray(pay2.BALX_LEN)
    d[0], d[1] = 1, 250
    _put(d, 8, day_limit); _put(d, 16, total_limit)
    for i, r in enumerate(repos):
        _put(d, 24 + 8 * i, r)
    if wf_sha:
        _put(d, 88, wf_sha.encode())
    _put(d, 128, day, signed=True); _put(d, 136, day_spent); _put(d, 144, total_spent)
    return bytes(d)


FEE_AMOUNTS = (0, 1, 5_000_000, 16_000_000, 20_000_000, 100_000_000, 500_000_000, 999_999_999, 1_000_000_000, 1_000_000_100,
               2_000_000_000, 5_000_000_000, 49_999_999_999, 50_000_000_000, 50_000_000_200, pay2.MAX_AMOUNT, 10 ** 12)
# upgrade feeds (web/upgrades.json's shape): which fee a page that asks no chain shows
FEEDS = {"2.1 pending": {"entries": [{"index": 4, "program": "knos_pay", "status": "pending"}]},
         "2.1 executed": {"entries": [{"index": 4, "program": "knos_pay", "status": "executed"}, {"index": 5, "program": "knos_meter", "status": "executed"}]},
         "2.2 pending": {"entries": [{"index": 8, "program": "knos_pay", "status": "pending"}, {"index": 4, "program": "knos_pay", "status": "executed"}]},
         "2.2 executed": {"entries": [{"index": 8, "program": "knos_pay", "status": "executed"}, {"index": 4, "program": "knos_pay", "status": "executed"}]},
         "another program after": {"entries": [{"index": 7, "program": "knos_oidc", "status": "executed"}, {"index": 4, "program": "knos_pay", "status": "executed"}]},
         "not a feed": {}}


def plan_bytes(owner_id=OWNER, fee_bps=100, expires=NOW + 90 * 86_400) -> bytes:
    d = bytearray(pay2.PLAN_LEN)
    d[0], d[1] = 1, 249
    _put(d, 2, fee_bps, 2); _put(d, 8, owner_id); _put(d, 16, expires, signed=True)
    return bytes(d)


def hb_bytes(payer: Pubkey, until: int, entries) -> bytes:
    """The record of a holdback (programs-v2/knos_pay/src/order_terms.rs, Hb): `entries` are (GitHub id, wallet, amount)."""
    d = bytearray(pay2.HB_LEN)
    d[0], d[1], d[2] = 1, 248, len(entries)
    _put(d, 8, payer); _put(d, 40, until, signed=True)
    for i, (payee, wallet, amount) in enumerate(entries):
        _put(d, 48 + 48 * i, payee); _put(d, 56 + 48 * i, wallet); _put(d, 88 + 48 * i, amount)
    return bytes(d)


def assign_bytes(payee: int, order: Pubkey, to: Pubkey, since: int) -> bytes:
    d = bytearray(pay2.AS_LEN)
    d[0], d[1] = 1, 247
    _put(d, 8, payee); _put(d, 16, order); _put(d, 48, to); _put(d, 80, since, signed=True)
    return bytes(d)


def used_bytes(payer: Pubkey, after: int) -> bytes:
    d = bytearray(pay2.USED_LEN)
    d[0] = 1
    _put(d, 1, payer); _put(d, 33, after, signed=True)
    return bytes(d)


def done_bytes(payer: Pubkey, order: Pubkey) -> bytes:
    return bytes([1]) + bytes(payer) + bytes(order)


def credits_bytes(*, token_program=0, decimals=6, owner_id=OWNER, authority, mint, spent=1_250_000, evaluations=10_025) -> bytes:
    d = bytearray(meter.CREDITS_LEN)
    d[0], d[1], d[2], d[3] = 1, 248, token_program, decimals
    _put(d, 8, owner_id); _put(d, 16, authority); _put(d, 48, mint); _put(d, 80, spent); _put(d, 88, evaluations)
    _put(d, 96, pay2.wf_repo_hash(WF_REPO)); _put(d, 128, WF_SHA.encode())
    return bytes(d)


def meter_plan_bytes(*, tier=2, month=202610, owner_id=OWNER, rate=20_000, expiry=NOW + 90 * 86_400, used=10_025) -> bytes:
    d = bytearray(meter.PLAN_LEN)
    d[0], d[1], d[2] = 1, 247, tier
    _put(d, 4, month, 4); _put(d, 8, owner_id); _put(d, 16, rate); _put(d, 24, expiry, signed=True); _put(d, 32, used)
    return bytes(d)


def mark_bytes(*, accepted=1, month=202610, buyer=OWNER, seller=MAINT, time=NOW, rate=2_000_000, fee=50_000, payer: Pubkey | None) -> bytes:
    """A mark as programs-v2/knos_meter/src/state.rs lays it out. `payer` None: one written before CloseMark existed (48 bytes, version 1)."""
    d = bytearray(meter.MARK_LEN if payer is not None else meter.MARK_LEN_1)
    d[0], d[1] = 2 if payer is not None else 1, accepted
    _put(d, 4, month, 4); _put(d, 8, buyer); _put(d, 16, seller); _put(d, 24, time, signed=True); _put(d, 32, rate); _put(d, 40, fee)
    if payer is not None:
        _put(d, 48, payer); _put(d, 80, meter.close_after(time), signed=True)
    return bytes(d)


def month_bytes(*, month=202610, buyer=OWNER, seller=MAINT, evaluations=9, accepted=7, rejected=2, value=14_000_000, fees=450_000) -> bytes:
    d = bytearray(meter.MONTH_LEN)
    d[0], d[1] = 1, 246
    _put(d, 4, month, 4)
    for at, v in ((8, buyer), (16, seller), (24, evaluations), (32, accepted), (40, rejected), (48, value), (56, fees)):
        _put(d, at, v)
    return bytes(d)


def ledger_bytes(*, claim=0, month=202610, buyer=OWNER, seller=MAINT, next_seq=2, evaluations=8, accepted=7, value=14_000_000, fees=150_000,
                 chain: bytes) -> bytes:
    """A Ledger as programs-v2/knos_meter/src/state.rs lays it out: byte 2 says whose count it is (0 the buyer's, 1 the seller's claim)."""
    d = bytearray(meter.LEDGER_LEN)
    d[0], d[2] = 1, claim
    _put(d, 4, month, 4); _put(d, 8, buyer); _put(d, 16, seller); _put(d, 24, next_seq); _put(d, 32, evaluations); _put(d, 40, accepted)
    _put(d, 48, value); _put(d, 56, fees)
    d[64:96] = chain
    return bytes(d)


def passkey_fund_section(k) -> dict:
    """knos-passkey's Fund (1.1) as src/knos/settle/v2/passkey_fund.py builds it: only the bytes are held here, the
    assertion is not a real one (tests/test_passkey_fund.py signs and sends real ones)."""
    key = bytes([2]) + bytes(range(1, 33))
    wallet = passkey2.wallet(key)
    terms = pay2.terms_json(TERMS)
    data = bytes(pay2.fund_order_wallet_ix(wallet, pay2.ata(wallet, k["mint"]), k["mint"], REPO, ISSUE, AMOUNT, WF_REPO, WF_SHA, terms, seq=2).data)
    scope = pay2.scope_of(REPO, ISSUE, bytes([7]) * 32)
    private = bytes(pay2.fund_order_wallet_ix(wallet, pay2.ata(wallet, k["mint22"], T22), k["mint22"], 0, 0, AMOUNT, WF_REPO, WF_SHA, pay2.terms_hash(terms),
                                              pay2.MERGE, 14 * 86_400, 1, pay2.opts(pay2.F_PRIVATE, salted=True), scope, T22).data)
    auth, cdj, sig, slot, nonce = bytes(range(37)), b'{"type":"webauthn.get","challenge":"x"}', bytes([1]) * 32 + bytes([2]) * 32, 400_000_123, 5
    return {
        "inputs": {"key": key.hex(), "mint": str(k["mint"]), "mint22": str(k["mint22"]), "from": str(k["dest_token"]), "expiry_slot": slot, "nonce": nonce,
                   "authenticator_data": auth.hex(), "client_data_json": cdj.decode(), "signature": sig.hex(), "data": data.hex(), "data (private)": private.hex()},
        "pay": str(pay2.PAY_ID), "wallet": str(wallet),
        "constants": {"FUND_ORDER_WALLET": passkey_fund.FUND_ORDER_WALLET, "FUND_MIN": passkey_fund.FUND_MIN},
        "errors": {str(code): words for code, words in passkey_fund.ERRORS.items()},
        "challenge": passkey_fund.fund_challenge(k["mint"], data, slot, nonce).hex(),
        "order": str(passkey_fund.order_of(wallet, data)), "order (private)": str(passkey_fund.order_of(wallet, private)),
        "ixs": [ix(i) for i in passkey_fund.fund_ixs(key, k["mint"], data, slot, nonce, auth, cdj, sig)],
        "ixs (private, token-2022, a token account given)": [ix(i) for i in passkey_fund.fund_ixs(key, k["mint22"], private, slot, nonce, auth, cdj, sig,
                                                                                                    token_program=T22, from_token=k["dest_token"])],
    }


def iss_bytes(url: str) -> bytes:
    return bytes([3, 245, 0, len(url.encode())]) + url.encode()


def key_bytes(n: int, *, state=1, issuer=oidc2.GITHUB, active_at=NOW - 86_400, expires_at=NOW + 29 * 86_400, flags=oidc2.APPROVED | oidc2.GENESIS,
              tail: bytes = b"") -> bytes:
    """A key account: the 40-byte header, then n and r2 as little-endian limbs, then (an issuer that is not GitHub or GitLab) the tail."""
    raw = oidc2.modulus_bytes(n)
    n0inv, r2 = oidc2.key_params(n)
    d = bytearray(oidc2.K_HDR)
    d[0], d[1], d[2], d[3] = state, issuer, len(raw) // 4, 252
    _put(d, 4, n0inv, 4); _put(d, 8, active_at, signed=True); _put(d, 16, expires_at, signed=True)
    d[24] = flags
    return bytes(d) + raw[::-1] + r2[::-1] + tail


def token_bytes(payload: bytes, *, stage=2, issuer=oidc2.GITHUB, done=16, exp=NOW + 300, key: Pubkey, payer: Pubkey) -> bytes:
    """A token account whose `jwt` is header.payload.signature with `payload` in the clear where the verifier leaves
    the decoded claims (payload_off, payload_len)."""
    jwt = b"eyJhbGciOiJSUzI1NiJ9." + payload + b".c2ln"
    d = bytearray(oidc2.T_JWT)
    d[0], d[1], d[2], d[3] = stage, issuer, done, 64
    _put(d, 4, len(jwt), 2); _put(d, 6, oidc2.T_JWT + 21, 2); _put(d, 8, len(payload), 2); _put(d, 10, exp, signed=True)
    _put(d, 18, key); _put(d, 50, payer); _put(d, 82, oidc2.token_id(jwt))
    return bytes(d) + jwt


def plain(value):
    """A reader's result as JSON: addresses as base58, bytes as hex, tuples as lists."""
    if dataclasses.is_dataclass(value):
        return {f.name: plain(getattr(value, f.name)) for f in dataclasses.fields(value)}
    if isinstance(value, Pubkey):
        return str(value)
    if isinstance(value, (bytes, bytearray)):
        return bytes(value).hex()
    if isinstance(value, (list, tuple)):
        return [plain(v) for v in value]
    return value


def transfer_checked_ix(source: Pubkey, mint: Pubkey, dest: Pubkey, owner: Pubkey, amount: int, decimals: int, token_program: Pubkey = pay2.TOKEN) -> Instruction:
    """SPL Token's TransferChecked: how a wallet adds money to a Balance (a plain transfer to its token account).
    tests/test_settle_fixtures.py runs this encoding against the token program itself."""
    return Instruction(token_program, bytes([TRANSFER_CHECKED]) + amount.to_bytes(8, "little") + bytes([decimals]),
                       [AccountMeta(source, False, True), AccountMeta(mint, False, False), AccountMeta(dest, False, True), AccountMeta(owner, True, False)])


def tx(ixs: list[Instruction], payer: Pubkey) -> dict:
    """The unsigned legacy transaction a wallet is handed: what solders makes of these instructions."""
    message = Message.new_with_blockhash(ixs, payer, BLOCKHASH)
    return {"payer": str(payer), "instructions": [ix(i) for i in ixs], "message": bytes(message).hex(),
            "transaction": base64.b64encode(bytes(Transaction.new_unsigned(message))).decode()}


def second() -> dict:
    k = K2
    terms, terms_tests = pay2.terms_json(TERMS), pay2.terms_json(TERMS_TESTS)
    th, th_tests = pay2.terms_hash(terms), pay2.terms_hash(terms_tests)
    bal, bal22, faucet_bal = pay2.balance_pda(OWNER, k["authority"], k["mint"]), pay2.balance_pda(OWNER, k["authority"], k["mint22"], ), pay2.faucet_balance_pda(OWNER)
    job_bal, job_wallet = pay2.job_pda(REPO, ISSUE, bal), pay2.job_pda(REPO, ISSUE, k["funder"])
    key2048, key4096 = oidc2.key_pda(oidc2.GITHUB, N2048), oidc2.key_pda(oidc2.GITLAB, N4096)
    accounts = {
        "job (open, from a Balance)": job_bytes(source=bal, refund_to=pay2.baltok_pda(bal), rent_to=k["relayer"], mint=k["mint"], terms=th,
                                                wf_repo=WF_REPO, wf_sha=WF_SHA),
        "job (held, from a wallet, Token-2022, tests mode)": job_bytes(state=3, mode=1, kind=0, token_program=1, hold_until=NOW + pay2.HOLD, payee=AUTHOR,
                                                                      funder_id=0, owner_id=0, not_before=NOW - pay2.CLOCK_SLACK, source=k["funder"],
                                                                      refund_to=k["funder"], rent_to=k["funder"], mint=k["mint22"], terms=th_tests,
                                                                      wf_repo=WF_REPO, wf_sha=WF_SHA),
        "job (open, faucet money)": job_bytes(faucet=1, amount=20_000_000, source=faucet_bal, refund_to=pay2.baltok_pda(faucet_bal), rent_to=k["relayer"],
                                              mint=pay2.faucet_mint(), terms=th, wf_repo=WF_REPO, wf_sha=WF_SHA),
        "balance": balance_bytes(authority=k["authority"], mint=k["mint"]),
        "balance (faucet)": balance_bytes(faucet=1, authority=pay2.auth_pda(), mint=pay2.faucet_mint(), cap=0, spenders=[], spent=0, last_iat=0),
        "bind": bind_bytes(AUTHOR, k["wallet"], NOW - 3600),
        "rep": rep_bytes(),
        "pause": (NOW + 3 * 86_400).to_bytes(8, "little", signed=True),
        "rate": NOW.to_bytes(8, "little", signed=True) + (NOW - 5).to_bytes(8, "little", signed=True),
    }
    readers = {"job": pay2.read_job, "balance": pay2.read_balance, "bind": pay2.read_bind, "rep": pay2.read_rep, "pause": pay2.read_pause,
               "rate": pay2.read_rate}
    jobs = {name: pay2.read_job(data) for name, data in accounts.items() if name.startswith("job")}
    j_bal, j_wallet = jobs["job (open, from a Balance)"], jobs["job (held, from a wallet, Token-2022, tests mode)"]
    bind = pay2.read_bind(accounts["bind"])
    fund_aud = pay2.fund_audience(ISSUE, AMOUNT, pay2.MERGE, th, bal)
    pay_aud = pay2.pay_audience(REPO, ISSUE, AUTHOR, HEAD, th, pay2.MERGE, k["address"])
    pay_aud_none = pay2.pay_audience(REPO, ISSUE, AUTHOR, HEAD, th_tests, pay2.TESTS)
    keys = {
        "ready, genesis": (key_bytes(N2048), NOW),
        "ready, 4096-bit, attested and approved": (key_bytes(N4096, issuer=oidc2.GITLAB, flags=oidc2.APPROVED), NOW),
        "not on chain": (None, NOW),
        "not a key account": (bytes(41), NOW),
        "registered, not ready": (key_bytes(N2048, state=0), NOW),
        "revoked": (key_bytes(N2048, flags=oidc2.APPROVED | oidc2.REVOKED), NOW),
        "new, not approved, still waiting": (key_bytes(N2048, active_at=NOW + 3600, expires_at=NOW + 31 * 86_400, flags=0), NOW),
        "new, not approved, wait over": (key_bytes(N2048, active_at=NOW - 60, flags=0), NOW),
        "approved, still waiting": (key_bytes(N2048, active_at=NOW + 3600, expires_at=NOW + 31 * 86_400, flags=oidc2.APPROVED), NOW),
        "expired": (key_bytes(N2048, active_at=NOW - 31 * 86_400, expires_at=NOW - 86_400), NOW),
        "expires this second": (key_bytes(N2048, expires_at=NOW), NOW),
    }
    token = token_bytes(json.dumps({"aud": fund_aud, "repository_id": str(REPO), "actor_id": str(MAINT), "iat": NOW}, separators=(",", ":")).encode(),
                        key=key2048, payer=k["relayer"])
    unverified = token_bytes(b"{}", stage=1, done=8, key=key2048, payer=k["relayer"])
    n_b64 = base64.urlsafe_b64encode(oidc2.modulus_bytes(N2048)).rstrip(b"=").decode()
    jwks = {"keys": [{"kty": "RSA", "kid": "k-2048", "alg": "RS256", "use": "sig", "e": "AQAB", "n": n_b64},
                     {"kty": "RSA", "kid": "no-alg", "e": "AQAB", "n": base64.urlsafe_b64encode(oidc2.modulus_bytes(N4096)).rstrip(b"=").decode()},
                     {"kty": "RSA", "kid": "other-exponent", "alg": "RS256", "e": "Aw", "n": n_b64},
                     {"kty": "RSA", "kid": "other-alg", "alg": "PS256", "e": "AQAB", "n": n_b64},
                     {"kty": "EC", "kid": "curve", "crv": "P-256", "x": "AA", "y": "AA"}]}
    wallet_tok = pay2.ata(k["authority"], k["mint"])
    wallet_tok22 = pay2.ata(k["authority"], k["mint22"], T22)
    open_ix = pay2.open_balance_ix(k["authority"], OWNER, k["mint"], CAP, SPENDERS)
    out = {
        "note": "The second deployment (programs-v2), from src/knos/settle/v2.",
        "programs": dict(pay2.IDS),
        "inputs": {**{n: str(v) for n, v in k.items()}, "repo_id": REPO, "issue": ISSUE, "payee_id": AUTHOR, "owner_id": OWNER, "maintainer_id": MAINT,
                   "spenders": SPENDERS, "cap": CAP, "amount": AMOUNT, "token_id": TID.hex(), "n2048": hex(N2048), "n4096": hex(N4096), "jwt": JWT,
                   "wf_repo": WF_REPO, "wf_sha": WF_SHA, "head_sha": HEAD, "now": NOW, "blockhash": str(BLOCKHASH), "terms": TERMS,
                   "terms_tests": TERMS_TESTS},
        "constants": {"MERGE": pay2.MERGE, "TESTS": pay2.TESTS, "FEE_BPS": pay2.FEE_BPS, "FEE_MIN": pay2.FEE_MIN, "MIN_AMOUNT": pay2.MIN_AMOUNT,
                      "MAX_AMOUNT": pay2.MAX_AMOUNT, "FAUCET_CAP": pay2.FAUCET_CAP, "MIN_WORK": pay2.MIN_WORK, "MAX_WORK": pay2.MAX_WORK,
                      "HOLD": pay2.HOLD, "PAUSE_MAX": pay2.PAUSE_MAX, "FUND_PERIOD": pay2.FUND_PERIOD, "CLOCK_SLACK": pay2.CLOCK_SLACK,
                      "MAX_TERMS": pay2.MAX_TERMS, "TOKEN_AHEAD": pay2.TOKEN_AHEAD, "TOKEN_LIFE": pay2.TOKEN_LIFE, "JOB_LEN": pay2.JOB_LEN,
                      "BALANCE_LEN": pay2.BALANCE_LEN, "BIND_LEN": pay2.BIND_LEN, "REP_LEN": pay2.REP_LEN, "KEY_DELAY": oidc2.KEY_DELAY,
                      "KEY_TTL": oidc2.KEY_TTL, "K_HDR": oidc2.K_HDR, "MAX_JWT": oidc2.MAX_JWT, "LATE": oidc2.LATE, "T_JWT": oidc2.T_JWT,
                      "CHUNK": oidc2.CHUNK, "GITHUB": oidc2.GITHUB, "GITLAB": oidc2.GITLAB, "TOKEN": str(pay2.TOKEN), "TOKEN_2022": str(T22),
                      "ATA_PROGRAM": str(pay2.ATA_PROGRAM), "SYSTEM": str(pay2.SYSTEM), "USDC_DEVNET": str(pay2.USDC_DEVNET)},
        "errors": {str(code): words for code, words in pay2.ERRORS.items()},
        "issuers": {str(i): {"issuer": oidc2.ISSUERS[i], "jwks": oidc2.JWKS[i]} for i in sorted(oidc2.ISSUERS)},
        "addresses": {
            "auth": str(pay2.auth_pda()), "vault(mint)": str(pay2.vault_pda(k["mint"])), "faucet_mint": str(pay2.faucet_mint()),
            "balance(owner, authority, mint)": str(bal), "faucet_balance(owner)": str(faucet_bal), "baltok(balance)": str(pay2.baltok_pda(bal)),
            "job(repo, issue, balance)": str(job_bal), "job(repo, issue, funder)": str(job_wallet), "bind(payee)": str(pay2.bind_pda(AUTHOR)),
            "rep(payee)": str(pay2.rep_pda(AUTHOR)), "pair(payee, owner id)": str(pay2.pair_pda(AUTHOR, OWNER)),
            "pair(payee, funder)": str(pay2.pair_pda(AUTHOR, k["funder"])), "rate(repo)": str(pay2.rate_pda(REPO)), "pause": str(pay2.pause_pda()),
            "ata(address, mint)": str(pay2.ata(k["address"], k["mint"])), "ata(address, mint22) token-2022": str(pay2.ata(k["address"], k["mint22"], T22)),
            "fee_account(mint)": str(pay2.ata(pay2.FEE_OWNER, k["mint"])), "token(payer, token_id)": str(oidc2.token_pda(k["payer"], TID)),
            "key(github, n2048)": str(key2048), "key(gitlab, n4096)": str(key4096),
        },
        "audiences": {
            "fund": fund_aud, "fund tests, 30 days": pay2.fund_audience(ISSUE, AMOUNT, pay2.TESTS, th_tests, faucet_bal, 30 * 86_400),
            "pay to an address": pay_aud, "pay, no address": pay_aud_none, "bind": pay2.bind_audience(k["wallet"]),
            "rotate": oidc2.rotate_audience(oidc2.GITHUB, N2048), "rotate 4096": oidc2.rotate_audience(oidc2.GITLAB, N4096),
            "named_balance(fund)": str(pay2.named_balance(fund_aud)),
            "destination(bind, pay to an address)": str(pay2.destination(bind, pay_aud)),
            "destination(no bind, pay to an address)": str(pay2.destination(None, pay_aud)),
            "destination(no bind, pay, no address)": pay2.destination(None, pay_aud_none),
        },
        "terms": {"json": terms.decode(), "hash": th.hex(), "json tests": terms_tests.decode(), "hash tests": th_tests.hex(),
                  # the client's own encoder, on text the terms never hold: every character that must be written as an escape
                  "odd": ODD, "json odd": pay2.terms_json(ODD).decode()},
        "hashes": {"wf_repo_hash": pay2.wf_repo_hash(WF_REPO).hex(), "funder_key(wallet)": pay2.funder_key(k["funder"]).hex(),
                   "funder_key(owner id)": pay2.funder_key(OWNER).hex(), "token_id(jwt)": oidc2.token_id(JWT).hex(),
                   "key_hash(n2048)": oidc2.key_hash(N2048).hex(), "key_hash(n4096)": oidc2.key_hash(N4096).hex()},
        "fees": {str(a): pay2.fee_of(a) for a in (0, 1, 50_000, 1_000_000, 2_000_000, 5_000_000, 20_000_000, 500_000_000)},
        "oidc": {"step_plan": {"2048": oidc2.step_plan(2048), "4096": oidc2.step_plan(4096)},
                 "key_params": {hex(n): {"n0inv": oidc2.key_params(n)[0], "r2": oidc2.key_params(n)[1].hex()} for n in (N2048, N4096, N2048_B)},
                 "jwks": jwks, "jwks_keys": [[kid, hex(n)] for kid, n in oidc2.jwks_keys(jwks)]},
        "instructions": {
            "oidc.write (first chunk)": ix(oidc2.write_ixs(k["payer"], TID, JWT)[0]),
            "oidc.write (last chunk)": ix(oidc2.write_ixs(k["payer"], TID, JWT)[-1]),
            "oidc.step": ix(oidc2.step_ix(k["payer"], TID, key2048, 8)),
            "oidc.close": ix(oidc2.close_ix(k["payer"], TID)),
            "oidc.register_key": ix(oidc2.register_key_ix(k["payer"], oidc2.GITHUB, N2048)),
            "oidc.register_key (attested, 4096)": ix(oidc2.register_key_ix(k["payer"], oidc2.GITLAB, N4096, k["attest"])),
            "oidc.key_params": ix(oidc2.key_params_ix(k["payer"], oidc2.GITHUB, N2048)),
            "oidc.key_params (4096)": ix(oidc2.key_params_ix(k["payer"], oidc2.GITLAB, N4096)),
            "oidc.refresh": ix(oidc2.refresh_ix(k["payer"], oidc2.GITHUB, N2048, k["attest"])),
            "oidc.approve": ix(oidc2.approve_ix(oidc2.GUARDIAN, oidc2.GITLAB, N4096)),
            "oidc.revoke": ix(oidc2.revoke_ix(oidc2.GUARDIAN, oidc2.GITHUB, N2048)),
            "pay.open_balance": ix(pay2.open_balance_ix(k["authority"], OWNER, k["mint"])),
            "pay.open_balance (cap, spenders)": ix(open_ix),
            "pay.open_balance (token-2022, four spenders)": ix(pay2.open_balance_ix(k["authority"], OWNER, k["mint22"], 0, [1, 2, 3, 2 ** 64 - 1], T22)),
            "pay.set_balance": ix(pay2.set_balance_ix(k["authority"], bal, CAP, SPENDERS)),
            "pay.set_balance (no cap, nobody)": ix(pay2.set_balance_ix(k["authority"], bal)),
            "pay.withdraw (everything)": ix(pay2.withdraw_ix(k["authority"], bal, k["mint"])),
            "pay.withdraw (amount, token account)": ix(pay2.withdraw_ix(k["authority"], bal, k["mint"], AMOUNT, k["dest_token"])),
            "pay.withdraw (token-2022)": ix(pay2.withdraw_ix(k["authority"], bal22, k["mint22"], 0, None, T22)),
            "pay.fund_balance": ix(pay2.fund_balance_ix(k["relayer"], k["token_account"], k["key"], bal, k["mint"], REPO, ISSUE, terms, used=JWT)),
            "pay.fund_balance (with its side account)": ix(pay2.fund_balance_ix(k["relayer"], k["token_account"], k["key"], bal, k["mint"], REPO, ISSUE, terms,
                                                                                balx=True, used=pay2.sig_hash(JWT))),
            "pay.fund_balance (faucet)": ix(pay2.fund_balance_ix(k["relayer"], k["token_account"], k["key"], faucet_bal, pay2.faucet_mint(), REPO, ISSUE, terms, used=token)),
            "pay.fund_wallet merge": ix(pay2.fund_wallet_ix(k["funder"], k["funder_token"], k["mint"], REPO, ISSUE, AMOUNT, WF_REPO, WF_SHA, terms)),
            "pay.fund_wallet tests (token-2022)": ix(pay2.fund_wallet_ix(k["funder"], k["funder_token"], k["mint22"], REPO, ISSUE, AMOUNT, WF_REPO, WF_SHA,
                                                                       terms_tests, pay2.TESTS, 7 * 86_400, T22)),
            "pay.pay (a Balance's job, to a wallet)": ix(pay2.pay_ix(k["relayer"], k["token_account"], k["key"], job_bal, j_bal, AUTHOR, k["wallet"], used=JWT)),
            "pay.pay (a Balance's job, held)": ix(pay2.pay_ix(k["relayer"], k["token_account"], k["key"], job_bal, j_bal, AUTHOR, None, used=pay2.sig_hash(JWT))),
            "pay.pay (a wallet's job, token account)": ix(pay2.pay_ix(k["relayer"], k["token_account"], k["key"], job_wallet, j_wallet, AUTHOR, k["wallet"],
                                                                      k["dest_token"], used=k["attest"])),
            "pay.pay (the marker of a token account's data)": ix(pay2.pay_ix(k["relayer"], k["token_account"], k["key"], job_bal, j_bal, AUTHOR, k["wallet"],
                                                                               used=token)),
            "pay.settle": ix(pay2.settle_ix(k["relayer"], job_wallet, j_wallet, k["wallet"])),
            "pay.refund (a Balance's job)": ix(pay2.refund_ix(k["relayer"], job_bal, j_bal)),
            "pay.refund (a wallet's job)": ix(pay2.refund_ix(k["relayer"], job_wallet, j_wallet)),
            "pay.refund (a wallet's job, token account)": ix(pay2.refund_ix(k["relayer"], job_wallet, j_wallet, k["dest_token"])),
            "pay.bind": ix(pay2.bind_ix(k["relayer"], k["token_account"], k["key"], AUTHOR, used=JWT)),
            "pay.pause": ix(pay2.pause_ix(pay2.GUARDIAN, k["payer"], 3 * 86_400)),
            "pay.pause (lift)": ix(pay2.pause_ix(pay2.GUARDIAN, k["payer"], 0)),
            "pay.init_faucet": ix(pay2.init_faucet_ix(k["payer"])),
            "pay.faucet_open": ix(pay2.faucet_open_ix(k["relayer"], k["token_account"], k["key"], OWNER, REPO, used=token)),
            "create_ata": ix(pay2.create_ata_ix(k["relayer"], k["address"], k["mint"])),
            "create_ata (token-2022)": ix(pay2.create_ata_ix(k["relayer"], k["address"], k["mint22"], T22)),
            "token.transfer_checked": ix(transfer_checked_ix(wallet_tok, k["mint"], pay2.baltok_pda(bal), k["authority"], AMOUNT, 6)),
        },
        "accounts": {name: {"data": data.hex(), "reader": name.split(" ")[0], "read": plain(readers[name.split(" ")[0]](data))}
                     for name, data in accounts.items()}
        | {"job (not a job)": {"data": bytes(319).hex(), "reader": "job", "read": plain(pay2.read_job(bytes(319)))},
           "balance (another version)": {"data": bytes(160).hex(), "reader": "balance", "read": plain(pay2.read_balance(bytes(160)))},
           "bind (none)": {"data": None, "reader": "bind", "read": plain(pay2.read_bind(None))},
           "rep (none)": {"data": None, "reader": "rep", "read": plain(pay2.read_rep(None))},
           "pause (none)": {"data": None, "reader": "pause", "read": pay2.read_pause(None)},
           "rate (none)": {"data": None, "reader": "rate", "read": plain(pay2.read_rate(None))},
           "token (verified)": {"data": token.hex(), "reader": "token", "read": plain(oidc2.read_token(token))},
           "token (stepping)": {"data": unverified.hex(), "reader": "token", "read": plain(oidc2.read_token(unverified))},
           "token (too short)": {"data": bytes(625).hex(), "reader": "token", "read": plain(oidc2.read_token(bytes(625)))}},
        "keys": {name: {"data": data.hex() if data is not None else None, "now": now, "read": plain(oidc2.read_key(data)),
                        "usable": list(oidc2.key_usable(oidc2.read_key(data), now))} for name, (data, now) in keys.items()},
        # What the site asks a wallet to sign, for the wallet K2["authority"] and the GitHub owner OWNER: the unsigned
        # legacy transaction as solders serialises it (the fee payer first, then each kind of account in key order).
        "transactions": {
            "open a balance": tx([open_ix], k["authority"]),
            "open a balance and put money in": tx([open_ix, transfer_checked_ix(wallet_tok, k["mint"], pay2.baltok_pda(bal), k["authority"], AMOUNT, 6)],
                                                  k["authority"]),
            "add money": tx([transfer_checked_ix(wallet_tok, k["mint"], pay2.baltok_pda(bal), k["authority"], AMOUNT, 6)], k["authority"]),
            "add money (token-2022, 9 decimals)": tx([transfer_checked_ix(wallet_tok22, k["mint22"], pay2.baltok_pda(bal22), k["authority"], 3 * 10 ** 9, 9, T22)],
                                                     k["authority"]),
            "set who may spend": tx([pay2.set_balance_ix(k["authority"], bal, CAP, SPENDERS)], k["authority"]),
            "take everything back": tx([pay2.create_ata_ix(k["authority"], k["authority"], k["mint"]), pay2.withdraw_ix(k["authority"], bal, k["mint"])],
                                       k["authority"]),
            "take an amount back": tx([pay2.create_ata_ix(k["authority"], k["authority"], k["mint"]),
                                       pay2.withdraw_ix(k["authority"], bal, k["mint"], AMOUNT)], k["authority"]),
            "a wallet funds a job": tx([pay2.fund_wallet_ix(k["funder"], pay2.ata(k["funder"], k["mint"]), k["mint"], REPO, ISSUE, AMOUNT, WF_REPO, WF_SHA,
                                                            terms)], k["funder"]),
        },
        "layouts": {
            "job (320 bytes)": "0 state u8 (1 open, 3 held) | 1 mode u8 | 2 kind u8 (0 wallet, 1 Balance) | 3 bump | 6 token_program u8 (0 Token, 1 Token-2022) | "
                               "7 faucet u8 | 8 repo_id u64 | 16 issue u64 | 24 amount u64 | 32 deadline i64 | 48 hold_until i64 | 56 payee u64 | "
                               "64 funder_id u64 | 72 not_before i64 | 80 owner_id u64 | 88 source[32] | 120 refund_to[32] | 152 rent_to[32] | 184 mint[32] | "
                               "216 terms[32] | 248 wf_repo_hash[32] | 280 wf_sha[40]",
            "balance (160 bytes)": "0 version u8 (1) | 1 bump | 2 faucet u8 | 8 owner_id u64 | 16 authority[32] | 48 mint[32] | 80 cap_per_job u64 (0: none) | "
                                   "88 last_iat i64 | 96 spenders [u64; 4] (0: empty) | 128 spent u64",
            "bind (56 bytes)": "0 version u8 (1) | 1 bump | 8 github user id u64 | 16 wallet[32] | 48 iat i64",
            "rep (64 bytes)": "0 paid u32 | 4 funders u32 | 8 total u64 | 16 test_paid u32 | 20 self_paid u32 | 32 test_total u64 | 40 first i64 | 48 last i64",
            "pause (8 bytes)": "0 until i64", "rate (16 bytes)": "0 last use i64 | 8 last iat i64",
            "token (626 + jwt bytes)": "as the first deployment's",
            "key (40 + 8 * limbs bytes)": "0 state u8 (1 ready) | 1 issuer u8 | 2 limbs u8 (64 or 128) | 3 bump u8 | 4 n0inv u32 | 8 active_at i64 | "
                                          "16 expires_at i64 | 24 flags u8 (1 approved, 2 revoked, 4 genesis, 8 private) | 40 n (LE limbs) | then r2 (LE limbs) | "
                                          "then, for an issuer that is not GitHub or GitLab, sha256(issuer URL)[32] and the registrant[32]",
            "order (512 bytes)": "0 version u8 (2) | 1 state u8 (1 open, 3 held, 4 warranty) | 2 mode u8 | 3 kind u8 (0 wallet, 1 Balance) | 4 flags u8 "
                                 "(1 faucet, 2 private, 4 neutral, 8 standing, 16 token-2022) | 5 bump | 6 decimals | 7 reserve_days | 8 repo_id u64 | "
                                 "16 issue u64 | 24 scope[32] | 56 seq u32 | 60 holdback_bps u16 | 62 kill_bps u16 | 64 amount u64 | 72 fee u64 | 80 rate u64 | "
                                 "88 paid u64 | 96 deadline i64 | 104 not_before i64 | 112 hold_until i64 | 120 warranty_s i64 | 128 reserved_by u64 | "
                                 "136 reserved_until i64 | 144 cancel_at i64 | 152 payee_id u64 | 160 funder_id u64 | 168 owner_id u64 | 176 arbiter_id u64 | "
                                 "184 judge_repo_id u64 | 192 source[32] | 224 refund_to[32] | 256 rent_to[32] | 288 mint[32] | 320 terms[32] | "
                                 "352 wf_repo_hash[32] | 384 wf_sha[40] | 424 fee_bps u16",
            "balx (152 bytes)": "0 version u8 (1) | 8 day_limit u64 | 16 total_limit u64 | 24 repos [u64; 8] | 88 wf_sha[40] | 128 day i64 | 136 day_spent u64 | "
                                "144 total_spent u64",
            "plan (24 bytes)": "0 version u8 (1) | 2 fee_bps u16 | 8 owner_id u64 | 16 expires i64",
            "iss (4 + url bytes)": "0 kind u8 (3) | 3 url length u8 | 4 issuer URL",
        },
    }
    _merge(out, orders(k, bal, token))
    out["meter"] = meter_section(k)
    out["passkey_fund"] = passkey_fund_section(k)
    out["v1"] = v1_section(k, terms)
    return out


def _merge(into: dict, more: dict) -> None:
    for name, value in more.items():
        if isinstance(value, dict) and isinstance(into.get(name), dict):
            overlap = set(value) & set(into[name])
            assert not overlap, overlap
            into[name].update(value)
        else:
            assert name not in into, name
            into[name] = value


URL = "https://token.example.com"
SALT = bytes(range(100, 132))
ORDER_TERMS = {"accept": "", "checks": [{"app": 15368, "name": "test"}], "deny": [".github/**"], "mode": "merge", "paths": [], "reserve": 7, "v": 1}
# who is paid, by the names of the inputs: [GitHub id, wallet, token account], as pay_order_ix takes them (a wallet of None: held)
FOUR_PAYEES = [[AUTHOR, "address"], [MAINT, "wallet", "dest_token"], [9, "rent_to"], [10, "payer"]]


def _payees(k, named) -> list[tuple]:
    return [(p[0], k[p[1]] if p[1] else None, *([k[p[2]]] if len(p) > 2 else [])) for p in named]


def orders(k, bal, token) -> dict:
    """What the second deployment's 2.1 build adds: orders, side accounts, plans, single-use markers, other issuers' keys."""
    scope, scope_private = pay2.scope_of(REPO, ISSUE), pay2.scope_of(REPO, ISSUE, SALT)
    o_terms = pay2.terms_json(ORDER_TERMS)
    o_hash = pay2.terms_hash(o_terms)
    bal22 = pay2.balance_pda(OWNER, k["authority"], k["mint22"])
    order_w, order_b, order_p = pay2.order_pda(scope, k["funder"], 0), pay2.order_pda(scope, bal, 3), pay2.order_pda(scope_private, k["funder"], 1)
    flagged = pay2.F_NEUTRAL | pay2.F_STANDING | pay2.F_TOKEN2022
    faucet_bal = pay2.faucet_balance_pda(OWNER)
    order_accounts = {
        "order (open, from a wallet, public)": order_bytes(scope=scope, source=k["funder"], refund_to=k["funder"], rent_to=k["funder"], mint=k["mint"],
                                                           terms=o_hash, kind=0, funder_id=0, owner_id=0),
        "order (warranty, from a Balance, standing, token-2022)": order_bytes(
            state=4, kind=1, flags=flagged, decimals=9, seq=3, holdback_bps=1500, kill_bps=500, rate=2_000_000_000, amount=40_000_000_000, fee=1_000_000_000,
            paid=6_000_000_000, hold_until=NOW + 5 * 86_400, warranty_s=14 * 86_400, reserved_by=AUTHOR, reserved_until=NOW + 86_400, cancel_at=NOW + 7 * 86_400,
            arbiter_id=9_001, scope=scope, source=bal, refund_to=pay2.baltok_pda(bal), rent_to=k["relayer"], mint=k["mint22"], terms=o_hash, fee_bps=100),
        "order (held, private)": order_bytes(state=3, flags=pay2.F_PRIVATE | pay2.F_NEUTRAL, repo=0, issue=0, payee=AUTHOR, judge_repo_id=70_000_001, scope=scope_private,
                                             source=k["funder"], refund_to=k["funder"], rent_to=k["funder"], mint=k["mint"], terms=o_hash, kind=0, seq=1,
                                             hold_until=NOW + pay2.HOLD),
        "order (open, faucet money)": order_bytes(flags=pay2.F_FAUCET | pay2.F_NEUTRAL, scope=scope, source=faucet_bal, refund_to=pay2.baltok_pda(faucet_bal),
                                                  rent_to=k["relayer"], mint=pay2.faucet_mint(), terms=o_hash),
        "order (open, cancelled while reserved)": order_bytes(scope=scope, source=k["funder"], refund_to=k["funder"], rent_to=k["funder"], mint=k["mint"], terms=o_hash,
                                                              kind=0, funder_id=0, owner_id=0, seq=2, kill_bps=1000, amount=20_000_000, fee=500_000,
                                                              reserved_by=MAINT, reserved_until=NOW + 86_400, cancel_at=NOW, deadline=NOW + pay2.NOTICE),
        "order (warranty, a holdback, from a wallet)": order_bytes(state=4, scope=scope, source=k["funder"], refund_to=k["funder"], rent_to=k["funder"], mint=k["mint"],
                                                                   terms=o_hash, kind=0, funder_id=0, owner_id=0, seq=5, holdback_bps=1000, paid=4_500_000,
                                                                   hold_until=NOW + 30 * 86_400, warranty_s=30 * 86_400),
        "order (open, a holdback, from a Balance)": order_bytes(scope=scope, seq=6, holdback_bps=2000, warranty_s=14 * 86_400, source=bal,
                                                                refund_to=pay2.baltok_pda(bal), rent_to=k["relayer"], mint=k["mint"], terms=o_hash),
        "holdback (one payee)": hb_bytes(k["relayer"], NOW + 30 * 86_400, [(AUTHOR, k["wallet"], 500_000)]),
        "holdback (three payees)": hb_bytes(k["payer"], NOW + 86_400, [(AUTHOR, k["address"], 300_000), (MAINT, k["wallet"], 150_000), (9, k["rent_to"], 50_001)]),
        "assign": assign_bytes(AUTHOR, order_w, k["dest_token"], NOW),
        "marker (used)": used_bytes(k["relayer"], NOW + pay2.USED_KEEP),
        "marker (done)": done_bytes(k["relayer"], order_b),
        "balx": balx_bytes(),
        "balx (no limits, any repository, any commit)": balx_bytes(day_limit=0, total_limit=0, repos=(), wf_sha="", day_spent=0, total_spent=0),
        "plan": plan_bytes(),
        "balance (with a side account)": balance_bytes(authority=k["authority"], mint=k["mint"], has_x=1),
        "iss (an issuer)": iss_bytes(URL),
    }
    readers = {"order": pay2.read_order, "balx": pay2.read_balx, "plan": pay2.read_plan, "balance": pay2.read_balance, "iss": oidc2.read_iss,
               "holdback": pay2.read_holdback, "assign": pay2.read_assign, "marker": pay2.read_marker}
    read = {name: pay2.read_order(data) for name, data in order_accounts.items() if name.startswith("order")}
    o_w, o_b, o_p = (read[n] for n in ("order (open, from a wallet, public)", "order (warranty, from a Balance, standing, token-2022)", "order (held, private)"))
    o_k, o_h, o_hb = (read[n] for n in ("order (open, cancelled while reserved)", "order (warranty, a holdback, from a wallet)", "order (open, a holdback, from a Balance)"))
    order_k, order_h, order_hb = pay2.order_pda(scope, k["funder"], 2), pay2.order_pda(scope, k["funder"], 5), pay2.order_pda(scope, bal, 6)
    hb_one, hb_three = pay2.read_holdback(order_accounts["holdback (one payee)"]), pay2.read_holdback(order_accounts["holdback (three payees)"])
    private_terms = pay2.private_fund_terms(scope_private, o_hash)
    opts_cases = {
        "none": pay2.opts(),
        "merge, reserve 7": pay2.opts(flags=pay2.F_NEUTRAL, reserve_days=7),
        "everything": pay2.opts(flags=pay2.F_NEUTRAL | pay2.F_STANDING, holdback_bps=5000, warranty_days=90, kill_bps=2000, reserve_days=30, rate=2_500_000,
                                arbiter_id=9_001, judge_repo_id=70_000_001, salted=True),
        "private": pay2.opts(flags=pay2.F_PRIVATE | pay2.F_NEUTRAL, salted=True, judge_repo_id=70_000_001),
    }
    fund_aud = pay2.order_fund_audience(ISSUE, AMOUNT, pay2.MERGE, o_hash, bal, 14 * 86_400, 3, opts_cases["merge, reserve 7"])
    one = [(AUTHOR, 10_000, k["address"])]
    many = [(AUTHOR, 6_000, k["address"]), (MAINT, 3_000, None), (9, 1_000, k["wallet"])]
    pay_one = pay2.order_pay_audience(order_w, HEAD, o_hash, pay2.MERGE, 12, one)
    pay_many = pay2.order_pay_audience(order_b, HEAD, o_hash, pay2.TESTS, 40, many)
    bound = pay2.read_bind(bind_bytes(AUTHOR, k["wallet"], NOW - 3600))
    tail_url, tail_private = oidc2.issuer_hash(URL) + bytes(32), oidc2.issuer_hash(URL) + bytes(k["authority"])
    keys = {
        "other issuer, attested and approved": (key_bytes(N2048, issuer=oidc2.OTHER, flags=oidc2.APPROVED, tail=tail_url), NOW),
        "other issuer, attested, not approved": (key_bytes(N2048, issuer=oidc2.OTHER, flags=0, active_at=NOW + 3600, tail=tail_url), NOW),
        "private, usable at once": (key_bytes(N2048, issuer=oidc2.PRIVATE, flags=oidc2.PRIVATE_FLAG, active_at=NOW - 60, tail=tail_private), NOW),
        "private, revoked": (key_bytes(N2048, issuer=oidc2.PRIVATE, flags=oidc2.PRIVATE_FLAG | oidc2.REVOKED, tail=tail_private), NOW),
        "private, expired": (key_bytes(N2048, issuer=oidc2.PRIVATE, flags=oidc2.PRIVATE_FLAG, expires_at=NOW - 1, tail=tail_private), NOW),
        "other issuer, no tail": (key_bytes(N2048, issuer=oidc2.OTHER, flags=oidc2.APPROVED), NOW),
    }
    issuer_token = bytearray(token)
    issuer_token[1] = oidc2.OTHER
    issuer_token[114:146] = oidc2.issuer_hash(URL)
    private_token = bytearray(issuer_token)
    private_token[1] = oidc2.PRIVATE
    private_token[146:178] = bytes(k["authority"])
    stepping = bytearray(issuer_token)
    stepping[0] = 1
    token_issuers = {"a token of another issuer": bytes(issuer_token), "a token of a private key": bytes(private_token), "a GitHub token": token,
                     "a token still being verified": bytes(stepping), "too short": bytes(625)}
    plans = {"no plan": None, "a plan in force": pay2.read_plan(plan_bytes()), "an expired plan": pay2.read_plan(plan_bytes(expires=NOW - 1)),
             "a rate below the floor": pay2.read_plan(plan_bytes(fee_bps=5)), "a rate above the cap": pay2.read_plan(plan_bytes(fee_bps=900)),
             "expires this second": pay2.read_plan(plan_bytes(expires=NOW))}
    four = _payees(k, FOUR_PAYEES)
    ixs = {
        "pay.version": ix(pay2.version_ix()),
        "pay.set_balance_x": ix(pay2.set_balance_x_ix(k["authority"], bal, 50_000_000, 500_000_000, [REPO, 7], WF_SHA)),
        "pay.set_balance_x (no limits)": ix(pay2.set_balance_x_ix(k["authority"], bal)),
        "pay.set_balance_x (eight repositories)": ix(pay2.set_balance_x_ix(k["authority"], bal, 1, 2, [1, 2, 3, 4, 5, 6, 7, 2 ** 64 - 1], "d" * 40)),
        "pay.set_plan": ix(pay2.set_plan_ix(pay2.FEE_OWNER, k["payer"], OWNER, 100, NOW + 90 * 86_400)),
        "pay.fund_order_wallet": ix(pay2.fund_order_wallet_ix(k["funder"], k["funder_token"], k["mint"], REPO, ISSUE, AMOUNT, WF_REPO, WF_SHA, o_terms)),
        "pay.fund_order_wallet (tests, options, seq, token-2022)": ix(pay2.fund_order_wallet_ix(
            k["funder"], k["funder_token"], k["mint22"], REPO, ISSUE, AMOUNT, WF_REPO, WF_SHA, o_terms, pay2.TESTS, 7 * 86_400, 4, opts_cases["everything"],
            token_program=T22)),
        "pay.fund_order_wallet (private)": ix(pay2.fund_order_wallet_ix(
            k["funder"], k["funder_token"], k["mint"], 0, 0, AMOUNT, WF_REPO, WF_SHA, o_hash, pay2.MERGE, 14 * 86_400, 1, opts_cases["private"], scope_private)),
        "pay.fund_order_balance": ix(pay2.fund_order_balance_ix(k["relayer"], k["token_account"], k["key"], bal, k["mint"], OWNER, REPO, ISSUE, o_terms, JWT, 3)),
        "pay.fund_order_balance (token-2022, marker given)": ix(pay2.fund_order_balance_ix(k["relayer"], k["token_account"], k["key"], bal22, k["mint22"], OWNER, REPO,
                                                                                            ISSUE, o_terms, k["attest"], 0, T22)),
        "pay.pay_order (one payee, a bound wallet)": ix(pay2.pay_order_ix(k["relayer"], k["token_account"], k["key"], order_w, o_w, [(AUTHOR, k["wallet"])], used=JWT)),
        "pay.pay_order (one payee, held)": ix(pay2.pay_order_ix(k["relayer"], k["token_account"], k["key"], order_w, o_w, [(AUTHOR, None)], used=k["attest"])),
        "pay.pay_order (four payees, a tip account, a token account)": ix(pay2.pay_order_ix(k["relayer"], k["token_account"], k["key"], order_b, o_b, four,
                                                                                            tip_token=k["dest_token"], used=JWT)),
        # the judges and the terms of an order (order_judge.rs, order_terms.rs)
        "pay.fund_order_balance (private)": ix(pay2.fund_private_order_balance_ix(k["relayer"], k["token_account"], k["key"], bal, k["mint"], OWNER, scope_private,
                                                                                    o_hash, JWT, 3)),
        "pay.bind_org": ix(pay2.bind_org_ix(k["relayer"], k["token_account"], k["key"], OWNER, used=JWT)),
        "pay.pay_order (a holdback: its record)": ix(pay2.pay_order_ix(k["relayer"], k["token_account"], k["key"], order_hb, o_hb,
                                                                       [(AUTHOR, k["wallet"]), (MAINT, k["address"])], used=JWT)),
        "pay.pay_order (a standing order: the pull request's marker)": ix(pay2.pay_order_ix(k["relayer"], k["token_account"], k["key"], order_b, o_b,
                                                                                           [(AUTHOR, k["wallet"])], pr=40, used=JWT)),
        "pay.release (one payee)": ix(pay2.release_ix(k["relayer"], order_h, o_h, hb_one)),
        "pay.release (three payees, a tip account, token-2022)": ix(pay2.release_ix(k["relayer"], order_b, o_b, hb_three, k["dest_token"])),
        "pay.revert (a wallet's order)": ix(pay2.revert_ix(k["relayer"], k["token_account"], k["key"], order_h, o_h, hb_one, used=JWT)),
        "pay.revert (a Balance's order)": ix(pay2.revert_ix(k["relayer"], k["token_account"], k["key"], order_b, o_b, hb_three, used=JWT)),
        "pay.revert (token account)": ix(pay2.revert_ix(k["relayer"], k["token_account"], k["key"], order_h, o_h, hb_one, k["dest_token"], used=JWT)),
        "pay.reserve": ix(pay2.reserve_ix(k["relayer"], k["token_account"], k["key"], order_w, used=JWT)),
        "pay.cancel (a wallet's order)": ix(pay2.cancel_ix(k["funder"], order_w)),
        "pay.cancel (a Balance's order, a token)": ix(pay2.cancel_ix(k["relayer"], order_b, k["token_account"], k["key"], used=JWT)),
        "pay.assign": ix(pay2.assign_ix(k["wallet"], order_w, AUTHOR, k["dest_token"])),
        "pay.close_marker (used)": ix(pay2.close_marker_ix(pay2.used_pda(JWT), k["relayer"])),
        "pay.close_marker (done)": ix(pay2.close_marker_ix(pay2.done_pda(order_b, 40), k["relayer"], order_b)),
        "pay.refund_order (a kill fee, to the taker)": ix(pay2.refund_order_ix(k["relayer"], order_k, o_k, kill_token=k["dest_token"])),
        "pay.refund_order (a kill fee, held for the taker)": ix(pay2.refund_order_ix(k["relayer"], order_k, o_k)),
        "pay.settle_order": ix(pay2.settle_order_ix(k["relayer"], order_p, o_p, k["wallet"])),
        "pay.settle_order (token account, tip account)": ix(pay2.settle_order_ix(k["relayer"], order_p, o_p, k["wallet"], k["dest_token"], k["token_account"])),
        "pay.refund_order (a wallet's order)": ix(pay2.refund_order_ix(k["relayer"], order_w, o_w)),
        "pay.refund_order (a Balance's order)": ix(pay2.refund_order_ix(k["relayer"], order_b, o_b)),
        "pay.refund_order (token account)": ix(pay2.refund_order_ix(k["relayer"], order_w, o_w, k["dest_token"])),
        "pay.top_up (a wallet's order)": ix(pay2.top_up_ix(k["funder"], order_w, o_w, 5_000_000)),
        "pay.top_up (a Balance's order)": ix(pay2.top_up_ix(k["authority"], order_b, o_b, 5_000_000_000)),
        "pay.top_up (token account)": ix(pay2.top_up_ix(k["funder"], order_w, o_w, 1, k["dest_token"])),
        "oidc.register_key (attested, with its key)": ix(oidc2.register_key_ix(k["payer"], oidc2.GITLAB, N4096, k["attest"], k["key"])),
        "oidc.register_key (no attestation, a key given)": ix(oidc2.register_key_ix(k["payer"], oidc2.GITHUB, N2048, None, k["key"])),
        "oidc.register_issuer_key": ix(oidc2.register_issuer_key_ix(k["payer"], URL, N2048, k["attest"], k["key"])),
        "oidc.register_private_key": ix(oidc2.register_private_key_ix(k["authority"], URL, N4096)),
        "oidc.key_params (issuer URL)": ix(oidc2.key_params_ix(k["payer"], URL, N2048)),
        "oidc.key_params (private)": ix(oidc2.key_params_ix(k["payer"], URL, N2048, registrant=k["authority"])),
        "oidc.refresh (with its key)": ix(oidc2.refresh_ix(k["payer"], oidc2.GITHUB, N2048, k["attest"], k["key"])),
        "oidc.refresh (issuer URL)": ix(oidc2.refresh_ix(k["payer"], URL, N2048, k["attest"], k["key"])),
        "oidc.approve (issuer URL)": ix(oidc2.approve_ix(oidc2.GUARDIAN, URL, N2048)),
        "oidc.revoke (private)": ix(oidc2.revoke_ix(k["authority"], URL, N2048, registrant=k["authority"])),
    }
    funds = pay2.fund_order_wallet_ix(k["funder"], pay2.ata(k["funder"], k["mint"]), k["mint"], REPO, ISSUE, AMOUNT, WF_REPO, WF_SHA, o_terms)
    return {
        "inputs": {"url": URL, "salt": SALT.hex(), "order_terms": ORDER_TERMS, "four_payees": FOUR_PAYEES, "head": HEAD},
        "constants": {"USDC_MAINNET": str(pay2.USDC_MAINNET), "COUNTED": [str(m) for m in pay2.COUNTED], "BALX_LEN": pay2.BALX_LEN, "PLAN_LEN": pay2.PLAN_LEN,
                      "ORDER_LEN": pay2.ORDER_LEN, "OPTS_LEN": pay2.OPTS_LEN, "FEE_VERSION": fees.NEW_VERSION, "MINTED": pay2.MINTED,
                      "TOKEN_AT": {str(tag): at for tag, at in pay2.TOKEN_AT.items()},
                      "ORDER_MIN_AMOUNT": pay2.ORDER_MIN_AMOUNT, "TIP": pay2.TIP, "TIP_FIRST": pay2.TIP_FIRST, "PLAN_BPS_MIN": pay2.PLAN_BPS_MIN,
                      "MAX_HOLDBACK_BPS": pay2.MAX_HOLDBACK_BPS, "MAX_WARRANTY_DAYS": pay2.MAX_WARRANTY_DAYS, "MAX_KILL_BPS": pay2.MAX_KILL_BPS,
                      "MAX_PAYEES": pay2.MAX_PAYEES, "HB_LEN": pay2.HB_LEN, "DONE_LEN": pay2.DONE_LEN, "AS_LEN": pay2.AS_LEN, "USED_LEN": pay2.USED_LEN,
                      "NOTICE": pay2.NOTICE, "USED_KEEP": pay2.USED_KEEP, "F_FAUCET": pay2.F_FAUCET, "F_PRIVATE": pay2.F_PRIVATE, "F_NEUTRAL": pay2.F_NEUTRAL,
                      "F_STANDING": pay2.F_STANDING, "F_TOKEN2022": pay2.F_TOKEN2022, "KEY_TAIL": oidc2.KEY_TAIL, "OTHER": oidc2.OTHER, "PRIVATE": oidc2.PRIVATE,
                      "PRIVATE_FLAG": oidc2.PRIVATE_FLAG, "MAX_ISS": oidc2.MAX_ISS, "T_IHASH": oidc2.T_IHASH},
        "addresses": {
            "order(scope, wallet, seq 0)": str(order_w), "order(scope, balance, seq 3)": str(order_b), "order(private scope, wallet, seq 1)": str(order_p),
            "ov(order)": str(pay2.ov_pda(order_w)), "balx(balance)": str(pay2.balx_pda(bal)), "plan(owner)": str(pay2.plan_pda(OWNER)),
            "used(jwt)": str(pay2.used_pda(JWT)), "used(token account data)": str(pay2.used_pda(token)), "used(signature hash)": str(pay2.used_pda(pay2.sig_hash(JWT))),
            "key(issuer url, n2048)": str(oidc2.key_pda(URL, N2048)), "key(private, n2048)": str(oidc2.key_pda(URL, N2048, registrant=k["authority"])),
            "iss(url)": str(oidc2.iss_pda(URL)),
            "hb(order)": str(pay2.hb_pda(order_w)), "done(order, pr 40)": str(pay2.done_pda(order_b, 40)), "assign(order, payee)": str(pay2.assign_pda(order_w, AUTHOR)),
        },
        "audiences": {
            "order fund": fund_aud, "order fund, no options": pay2.order_fund_audience(ISSUE, AMOUNT, pay2.TESTS, o_hash, bal),
            "order pay, one payee": pay_one, "order pay, three payees": pay_many, "payees_of(one)": plain(pay2.payees_of(pay_one)),
            "payees_of(three)": plain(pay2.payees_of(pay_many)), "payees_text(three)": pay2.payees_text(many),
            "order_destination(bind, address)": str(pay2.order_destination(bound, k["address"])),
            "order_destination(bind, no address)": str(pay2.order_destination(bound, None)),
            "order_destination(no bind, address)": str(pay2.order_destination(None, k["address"])),
            "order_destination(no bind, no address)": pay2.order_destination(None, None),
            "rotate (issuer url)": oidc2.rotate_audience(URL, N2048),
            "order fund, private": pay2.order_fund_audience(0, AMOUNT, pay2.MERGE, private_terms, bal, 14 * 86_400, 3, opts_cases["private"]),
            "rule, three payees": pay2.rule_audience(order_b, many), "org bind": pay2.org_bind_audience(k["wallet"]),
            "take": pay2.take_audience(order_w, AUTHOR, 7), "cancel": pay2.cancel_audience(order_b), "revert": pay2.revert_audience(order_b, HEAD),
            "payees_of(rule)": plain(pay2.payees_of(pay2.rule_audience(order_b, many))),
        },
        "hashes": {
            "scope(repo, issue)": scope.hex(), "scope(repo, issue, salt)": scope_private.hex(), "sig_hash(jwt)": pay2.sig_hash(JWT).hex(),
            "sig_hash(token account data)": pay2.sig_hash(token).hex(), "issuer_hash(url)": oidc2.issuer_hash(URL).hex(), "order terms": o_hash.hex(),
            "private_fund_terms(scope, terms)": private_terms.hex(),
        },
        "order terms": {"json": o_terms.decode(), "hash": o_hash.hex()},
        # the fee of the build in this tree (knos.fees.NEW: 0.3.18, knos_pay 2.2) ...
        "order fees": {f"{a}/{bps}/{dec}": fees.NEW.order(a, bps, dec) for a in FEE_AMOUNTS for bps, dec in ((30, 6), (20, 6), (10, 6), (30, 9), (30, 2))},
        "fees (decimals)": {f"{a}/{dec}": pay2.fee_of(a, dec) for a in (0, 1, 50_000, 1_000_000, 5_000_000_000) for dec in (2, 6, 9)},
        # ... and the 0.3.14 fee, which the public program charges until the upgrade to knos_pay 2.2 executes
        "order fees 0.3.14": {f"{a}/{bps}/{dec}": fees.OLD.order(a, bps, dec) for a in FEE_AMOUNTS for bps, dec in ((250, 6), (100, 6), (50, 6), (250, 9), (250, 2))},
        "fees 0.3.14 (decimals)": {f"{a}/{dec}": fees.OLD.job(a, dec) for a in (0, 1, 50_000, 1_000_000, 5_000_000_000) for dec in (2, 6, 9)},
        "fee rules": {name: {**dataclasses.asdict(r), "tiers": [list(t) for t in r.tiers]} for name, r in (("new", fees.NEW), ("old", fees.OLD))},
        "fee version of a feed": {name: fees.feed_version(feed) for name, feed in FEEDS.items()},
        "units": {f"{m}/{dec}": pay2.units(m, dec) for m in (0, 1, 400_000, 25_000_000, 5_000_000) for dec in (0, 2, 6, 9)},
        "plan bps": {name: fees.NEW.plan_bps(plan, NOW) for name, plan in plans.items()},
        "plan bps 0.3.14": {name: fees.OLD.plan_bps(plan, NOW) for name, plan in plans.items()},
        # what a refund owes a taker first, by the order it is read from
        "kill fees": {name: pay2.kill_fee(o) for name, o in read.items()},
        # where one payee of an order is paid: its assignee, else the address the token carries, else its bound wallet
        "payee wallets": {
            "assigned": plain(pay2.payee_wallet(order_accounts["assign"], o_w, bound, k["address"])),
            "assigned for an earlier order at this address": plain(pay2.payee_wallet(assign_bytes(AUTHOR, order_w, k["dest_token"], NOW - 1), o_w, bound, None)),
            "no assignment, an address": plain(pay2.payee_wallet(None, o_w, bound, k["address"])),
            "no assignment, no address, no bind": pay2.payee_wallet(None, o_w, None, None),
        },
        # whether a token is used up, from its marker: one the devnet faucet made still funds once
        "spent": {name: {"data": None if data is None else data.hex(), "want": pay2.spent(data)}
                  for name, data in {"no marker": None, "used": used_bytes(k["relayer"], NOW + pay2.USED_KEEP),
                                     "minted on by the faucet": bytes([pay2.MINTED]) + used_bytes(k["relayer"], NOW + pay2.USED_KEEP)[1:]}.items()},
        "opts": {name: o.hex() for name, o in opts_cases.items()},
        "order instructions": ixs,
        "order accounts": {name: {"data": data.hex(), "reader": name.split(" ")[0], "read": plain(readers[name.split(" ")[0]](data))}
                           for name, data in order_accounts.items()}
        | {"order (not an order)": {"data": bytes(511).hex(), "reader": "order", "read": plain(pay2.read_order(bytes(511)))},
           "order (another version)": {"data": bytes(512).hex(), "reader": "order", "read": plain(pay2.read_order(bytes(512)))},
           "balx (none)": {"data": None, "reader": "balx", "read": plain(pay2.read_balx(None))},
           "plan (none)": {"data": None, "reader": "plan", "read": plain(pay2.read_plan(None))},
           "holdback (none)": {"data": None, "reader": "holdback", "read": plain(pay2.read_holdback(None))},
           "assign (not one)": {"data": bytes(88).hex(), "reader": "assign", "read": plain(pay2.read_assign(bytes(88)))},
           "marker (neither kind)": {"data": bytes(64).hex(), "reader": "marker", "read": plain(pay2.read_marker(bytes(64)))},
           "iss (not one)": {"data": bytes([3, 0, 0, 9, 1]).hex(), "reader": "iss", "read": oidc2.read_iss(bytes([3, 0, 0, 9, 1]))}},
        "order keys": {name: {"data": data.hex(), "now": now, "read": plain(oidc2.read_key(data)), "usable": list(oidc2.key_usable(oidc2.read_key(data), now))}
                       for name, (data, now) in keys.items()},
        "token issuers": {name: {"data": data.hex(), "read": plain(oidc2.token_issuer(data))} for name, data in token_issuers.items()},
        "order transactions": {
            "a wallet funds an order": tx([funds], k["funder"]),
            "a wallet funds an order, with its token account": tx([pay2.create_ata_ix(k["funder"], k["funder"], k["mint"]), funds], k["funder"]),
        },
    }


BUYER_ID, SELLER_ID = OWNER, MAINT
ORDER32, POLICY32 = bytes([0xA1]) * 32, bytes([0xB2]) * 32
METER = Pubkey.from_string(pay2.IDS["knos_meter"])


def _eval_line(*, buyer=BUYER_ID, seller=SELLER_ID, order=ORDER32, artifact="a" * 40, policy=POLICY32, milestone=0, verdict=1, rate=2_000_000, fee=0, month=202610,
               n=1, mint=None) -> str:
    """The line knos_meter's Record prints (programs-v2/knos_meter/src/meter.rs), as the runtime shows it."""
    return (f"Program log: knosm:eval buyer={buyer} seller={seller} order={order.hex()} artifact={artifact} policy={policy.hex()} milestone={milestone} "
            f"verdict={verdict} rate={rate} fee={fee} month={month} n={n} mint={mint}")


def _tx(program: Pubkey, *lines: str, other: Pubkey | None = None) -> list[str]:
    """The log of a transaction in which `program` printed `lines` (and `other` a program of someone else's printed the same kind of line)."""
    head = ["Program ComputeBudget111111111111111111111111111111 invoke [1]", "Program ComputeBudget111111111111111111111111111111 success"]
    mine = [f"Program {program} invoke [1]", *lines, f"Program {program} success"]
    return head + mine if other is None else head + [f"Program {other} invoke [1]", *lines, f"Program {other} success"] + mine[:1] + mine[-1:]


class _Ledger:
    """What meter.statement reads: the transactions that named an address, newest first, and the log of each."""
    def __init__(self, logs: list[list[str]]):
        self.logs_by = {f"sig{i}": log for i, log in enumerate(logs)}

    def history(self, address, most=500):
        yield from list(self.logs_by)[:most]

    def logs(self, signature):
        return self.logs_by[signature]


def meter_section(k) -> dict:
    """knos-meter's addresses, audiences, instructions, account readers and the statement recomputed from logs."""
    mint, mint22 = k["mint"], k["mint22"]
    credits, credits22 = meter.credits_pda(OWNER, k["authority"], mint), meter.credits_pda(OWNER, k["authority"], mint22)
    c = meter.read_credits(credits_bytes(authority=k["authority"], mint=mint))
    c22 = meter.read_credits(credits_bytes(token_program=1, decimals=9, authority=k["authority"], mint=mint22))
    aud = meter.eval_audience(BUYER_ID, SELLER_ID, ORDER32, "a" * 40, POLICY32, 0, 1, 2_000_000)
    aud_rejected = meter.eval_audience(BUYER_ID, SELLER_ID, ORDER32, "b" * 40, POLICY32, 3, 0, 5)
    e, e_rejected = meter.parse_audience(aud), meter.parse_audience(aud_rejected)
    when = {"2026-10-03": NOW, "the first second of a month": 1_788_220_800, "the last second of a month": 1_788_220_799, "a year end": 1_798_761_599,
            "before 1970": -5, "epoch": 0}
    plans = {"no plan, nothing used": meter.read_plan(None), "a plan, past the free ones": meter.read_plan(meter_plan_bytes()),
             "a plan, expired": meter.read_plan(meter_plan_bytes(expiry=NOW - 1)), "a plan, last month's count": meter.read_plan(meter_plan_bytes(month=202609)),
             "inside the free ones": meter.read_plan(meter_plan_bytes(used=9_999, rate=0, expiry=0, tier=0)),
             "the first one paid for": meter.read_plan(meter_plan_bytes(used=10_000, rate=0, expiry=0, tier=0))}
    accounts = {
        "credits": credits_bytes(authority=k["authority"], mint=mint), "credits (token-2022)": credits_bytes(token_program=1, decimals=9, authority=k["authority"], mint=mint22),
        "plan": meter_plan_bytes(), "mark": mark_bytes(payer=k["relayer"]), "mark (rejected)": mark_bytes(accepted=0, rate=5, fee=0, payer=k["relayer"]),
        "mark (from before CloseMark)": mark_bytes(payer=None), "month": month_bytes(),
    }
    marks = [(meter.mark_pda(BUYER_ID, bytes([n]) * 32), meter.read_mark(mark_bytes(time=t, payer=k["relayer"])))
             for n, t in ((1, NOW), (2, NOW - 40 * 86_400), (3, 1_788_220_799))]
    marks.append((meter.mark_pda(BUYER_ID, bytes([4]) * 32), meter.read_mark(mark_bytes(payer=None))))
    readers = {"credits": meter.read_credits, "plan": meter.read_plan, "mark": meter.read_mark, "month": lambda raw: meter.read_month(raw, OWNER, MAINT, 202610)}
    # a month, as the log lines say it: two accepted, one rejected, one retried (the same evaluation), one forged by another program, one of another seller,
    # one of another month; a transaction that failed prints nothing the runtime keeps
    other = Pubkey(bytes([0x77]) * 32)
    logs = [
        _tx(METER, _eval_line(n=1)),
        _tx(METER, _eval_line(artifact="b" * 40, verdict=0, rate=5, n=2, fee=50_000)),
        _tx(METER, _eval_line(artifact="c" * 40, milestone=1, rate=3_000_000, n=3, fee=50_000)),
        _tx(METER, "Program log: knosm:retry buyer=424242 key=00"),
        _tx(METER, _eval_line(n=1)),
        _tx(METER, _eval_line(artifact="d" * 40, n=4), other=other),
        _tx(METER, _eval_line(seller=1, artifact="e" * 40)),
        _tx(METER, _eval_line(month=202611, artifact="f" * 40)),
        ["Program log: knosm:eval not parsed"],
    ]
    statement = meter.statement(_Ledger(logs), BUYER_ID, SELLER_ID, 202610, METER)
    # the batch mode: four evaluations in one token, the buyer's count and the seller's claim of it
    ids = sorted(meter.parse_audience(meter.eval_audience(BUYER_ID, SELLER_ID, ORDER32, "a" * 40, POLICY32, n, 1, 2_000_000)).key for n in range(5))
    roots = {str(n): meter.merkle_root(ids[:n]) for n in (1, 2, 3, 5)}
    b_aud = meter.batch_audience(BUYER_ID, SELLER_ID, 202610, 3, 5, 4, 8_000_000, roots["5"])
    c_aud = meter.batch_audience(BUYER_ID, SELLER_ID, 202610, 0, 5, 5, 10_000_000, roots["5"], "claim")
    chain0 = meter.chain_hash(bytes(32), roots["3"], 0, 3, 3, 6_000_000)
    ledgers = {"ledger": ledger_bytes(chain=meter.chain_hash(chain0, roots["5"], 1, 5, 4, 8_000_000)),
               "ledger (the seller's claim)": ledger_bytes(claim=1, next_seq=1, evaluations=5, accepted=5, value=10_000_000, fees=0, chain=chain0)}
    return {
        "inputs": {"order": ORDER32.hex(), "policy": POLICY32.hex(), "artifact": "a" * 40, "other_program": str(other)},
        "constants": {"MICRO": meter.MICRO, "FEE": meter.FEE, "PLAN_MIN": meter.PLAN_MIN, "FREE_PER_MONTH": meter.FREE_PER_MONTH, "MIN_DECIMALS": meter.MIN_DECIMALS,
                      "MAX_DECIMALS": meter.MAX_DECIMALS, "EXTENSIONS": list(meter.EXTENSIONS), "CREDITS_LEN": meter.CREDITS_LEN, "PLAN_LEN": meter.PLAN_LEN,
                      "MARK_LEN": meter.MARK_LEN, "MARK_LEN_1": meter.MARK_LEN_1, "MARK_PAYER": meter.MARK_PAYER, "MARK_GRACE": meter.MARK_GRACE,
                      "MONTH_LEN": meter.MONTH_LEN, "WORKFLOWS": list(meter.WORKFLOWS), "EVAL": meter.EVAL, "CLOSED": meter.CLOSED,
                      "LEDGER_LEN": meter.LEDGER_LEN, "MAX_BATCH": meter.MAX_BATCH},
        "errors": {str(code): words for code, words in (meter.ERRORS | meter.BATCH_ERRORS).items()},
        "addresses": {
            "auth": str(meter.auth_pda()), "credits(owner, authority, mint)": str(credits), "credits(owner, authority, mint22)": str(credits22),
            "crtok(credits)": str(meter.crtok_pda(credits)), "plan(owner)": str(meter.plan_pda(OWNER)), "mark(buyer, key)": str(meter.mark_pda(BUYER_ID, e.key)),
            "month(buyer, seller, month)": str(meter.month_pda(BUYER_ID, SELLER_ID, 202610)),
            "ledger(buyer, seller, month)": str(meter.ledger_pda(BUYER_ID, SELLER_ID, 202610)),
            "ledger(buyer, seller, month, claim)": str(meter.ledger_pda(BUYER_ID, SELLER_ID, 202610, True)),
        },
        "audiences": {"eval": aud, "eval, rejected": aud_rejected, "parse(eval)": plain(e), "parse(rejected)": plain(e_rejected)},
        "hashes": {"eval_key": e.key.hex(), "eval_key (rejected)": e_rejected.key.hex()},
        "yyyymm": {name: meter.yyyymm(t) for name, t in when.items()},
        "when": when,
        "next_month": {name: meter.next_month(t) for name, t in when.items()},
        "close_after": {name: meter.close_after(t) for name, t in when.items()},
        # the marks one relayer paid for (the last one is from before CloseMark), and the ones CloseMark takes at each time
        "closable": {"marks": [[str(a), plain(m)] for a, m in marks],
                     "want": {str(t): [str(a) for a in meter.closable(marks, t)] for t in (NOW, meter.close_after(NOW) - 1, meter.close_after(NOW))}},
        "fee_units": {f"{rate}/{dec}": meter.fee_units(rate, dec) for rate in (0, 1, 20_000, 50_000, 2_000_000) for dec in (2, 6, 9, 18)},
        "quote": {name: meter.quote(plan, 6, NOW) for name, plan in plans.items()},
        "rate_at": {name: plan.rate_at(NOW) for name, plan in plans.items()},
        "used_in": {name: plan.used_in(202610) for name, plan in plans.items()},
        "plans": {name: plain(plan) for name, plan in plans.items()},
        "instructions": {
            "open_credits": ix(meter.open_credits_ix(k["authority"], OWNER, mint, WF_REPO, WF_SHA)),
            "open_credits (token-2022)": ix(meter.open_credits_ix(k["authority"], OWNER, mint22, WF_REPO, WF_SHA, T22)),
            "deposit": ix(meter.deposit_ix(pay2.ata(k["authority"], mint), k["authority"], credits, mint, AMOUNT, 6)),
            "deposit (token-2022)": ix(meter.deposit_ix(pay2.ata(k["authority"], mint22, T22), k["authority"], credits22, mint22, 3 * 10 ** 9, 9, T22)),
            "withdraw_credits (everything)": ix(meter.withdraw_credits_ix(k["authority"], credits, mint)),
            "withdraw_credits (amount, token account)": ix(meter.withdraw_credits_ix(k["authority"], credits, mint, AMOUNT, k["dest_token"])),
            "withdraw_credits (token-2022)": ix(meter.withdraw_credits_ix(k["authority"], credits22, mint22, 0, None, T22)),
            "set_plan": ix(meter.set_plan_ix(meter.FEE_OWNER, k["payer"], OWNER, 2, 20_000, NOW + 90 * 86_400)),
            "record (a fee token account given)": ix(meter.record_ix(k["relayer"], k["token_account"], k["key"], credits, c, aud, NOW, k["dest_token"])),
            "record (token-2022, the fee owner's own)": ix(meter.record_ix(k["relayer"], k["token_account"], k["key"], credits22, c22, aud_rejected, NOW + 40 * 86_400)),
            "close_mark": ix(meter.close_mark_ix(k["relayer"], meter.mark_pda(BUYER_ID, e.key))),
            "record_batch (a fee token account given)": ix(meter.record_batch_ix(k["relayer"], k["token_account"], k["key"], credits, c, b_aud, k["dest_token"])),
            "record_batch (token-2022, the fee owner's own)": ix(meter.record_batch_ix(k["relayer"], k["token_account"], k["key"], credits22, c22, b_aud)),
            "claim_batch": ix(meter.claim_batch_ix(k["relayer"], k["token_account"], k["key"], c_aud)),
            "version": ix(meter.version_ix()),
        },
        "batch": {"keys": [i.hex() for i in ids], "roots": {n: r.hex() for n, r in roots.items()}, "audience": b_aud, "claim audience": c_aud,
                  "chain": {"after the first batch (3, all accepted, 6000000)": chain0.hex(),
                            "after the second (5, 4 accepted, 8000000)": meter.chain_hash(chain0, roots["5"], 1, 5, 4, 8_000_000).hex()}},
        "ledgers": {name: {"data": data.hex(), "read": plain(meter.read_ledger(data))} for name, data in ledgers.items()}
        | {"ledger (none)": {"data": None, "read": None}, "ledger (not one)": {"data": bytes(95).hex(), "read": None}},
        "accounts": {name: {"data": data.hex(), "reader": name.split(" ")[0], "read": plain(readers[name.split(" ")[0]](data))} for name, data in accounts.items()}
        | {"credits (not credits)": {"data": bytes(167).hex(), "reader": "credits", "read": plain(meter.read_credits(bytes(167)))},
           "plan (none)": {"data": None, "reader": "plan", "read": plain(meter.read_plan(None))},
           "mark (none)": {"data": None, "reader": "mark", "read": plain(meter.read_mark(None))},
           "month (none)": {"data": None, "reader": "month", "read": plain(meter.read_month(None, OWNER, MAINT, 202610))}},
        "parse_eval": {line: plain(meter.parse_eval(line)) for line in ("knosm:eval a=1 b=two c=x=y", "knosm:retry buyer=1", "not a line", "knosm:eval")},
        "said": {"logs": _tx(METER, "Program log: one", "Program log: two", other=other), "program": str(METER),
                 "want": chain.said(_tx(METER, "Program log: one", "Program log: two", other=other), METER),
                 "want (everyone)": chain.said(_tx(METER, "Program log: one", "Program log: two", other=other))},
        "statement": {"logs": logs, "program": str(METER), "buyer": BUYER_ID, "seller": SELLER_ID, "month": 202610, "want": plain(statement)},
    }


def v1_section(k, terms) -> dict:
    """The unsigned v1 transaction (SIMD-0385, 4,096 bytes, the compute budget inside the message) as solders writes it."""
    bal = pay2.balance_pda(OWNER, k["authority"], k["mint"])
    o_terms = pay2.terms_json(ORDER_TERMS)
    o_hash = pay2.terms_hash(o_terms)
    scope = pay2.scope_of(REPO, ISSUE)
    order_b = pay2.order_pda(scope, bal, 3)
    o_b = pay2.read_order(order_bytes(state=1, kind=1, flags=pay2.F_NEUTRAL, scope=scope, source=bal, refund_to=pay2.baltok_pda(bal), rent_to=k["relayer"],
                                      mint=k["mint"], terms=o_hash))
    four = _payees(k, FOUR_PAYEES)
    pay_four = pay2.pay_order_ix(k["relayer"], k["token_account"], k["key"], order_b, o_b, four, used=JWT)
    open_ix = pay2.open_balance_ix(k["authority"], OWNER, k["mint"], CAP, SPENDERS)
    fund = pay2.fund_order_wallet_ix(k["funder"], pay2.ata(k["funder"], k["mint"]), k["mint"], REPO, ISSUE, AMOUNT, WF_REPO, WF_SHA, o_terms)
    wallet_tok = pay2.ata(k["authority"], k["mint"])
    cases = {
        "four payees, a compute limit": ([pay_four], k["relayer"], dict(compute_unit_limit=400_000)),
        "a wallet funds an order, every setting": ([fund], k["funder"], dict(compute_unit_limit=100_000, priority_fee=2_500, loaded_accounts_data_size_limit=64_000,
                                                                          heap_size=65_536)),
        "open a balance and put money in": ([open_ix, transfer_checked_ix(wallet_tok, k["mint"], pay2.baltok_pda(bal), k["authority"], AMOUNT, 6)], k["authority"],
                                            dict(compute_unit_limit=60_000, priority_fee=1)),
        "a token-2022 payee list and a heap": ([pay2.create_ata_ix(k["relayer"], k["address"], k["mint22"], T22), pay_four], k["relayer"],
                                               dict(compute_unit_limit=1_400_000, heap_size=32_768)),
    }
    out = {}
    for name, (ixs, payer, cfg) in cases.items():
        message = MessageV1.try_compile(payer, ixs, BLOCKHASH, TransactionConfig(**cfg))
        wire = to_bytes_versioned(message)
        signers = message.header.num_required_signatures
        out[name] = {"payer": str(payer), "config": cfg, "instructions": [ix(i) for i in ixs], "message": wire.hex(),
                     "transaction": base64.b64encode(wire + bytes(64 * signers)).decode(), "size": len(wire) + 64 * signers}
    return {"cases": out, "limits": {"MAX_TRANSACTION_SIZE": MessageV1.MAX_TRANSACTION_SIZE if hasattr(MessageV1, "MAX_TRANSACTION_SIZE") else 4096,
                                    "V1_PREFIX": 0x81}}


if __name__ == "__main__":
    text = json.dumps(build(), indent=1) + "\n"
    if "--check" in sys.argv:
        sys.exit(0 if OUT.exists() and OUT.read_text(encoding="utf-8") == text else "sdk/settle/fixtures.json is stale: run python scripts/settle_fixtures.py")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT} ({len(text)} bytes)")
