"""Write sdk/settle/fixtures.json: knos-oidc and knos-pay addresses, audiences, instructions and accounts encoded by
the Python client (the authority, src/knos/settle), so any other client (the web app's JavaScript, an npm package, a
program doing CPI) can check its encodings byte for byte, offline.  Run: python scripts/settle_fixtures.py
`--check` exits 1 if the file on disk is stale.
"""
import json
import sys
from pathlib import Path

from solders.pubkey import Pubkey

from knos.settle import oidc, pay

OUT = Path(__file__).resolve().parents[1] / "sdk" / "settle" / "fixtures.json"
NAMES = ["payer", "funder", "funder_token", "mint", "relayer", "address", "rent_to", "token_account"]
K = {n: Pubkey(bytes([i + 1]) * 32) for i, n in enumerate(NAMES)}
REPO, ISSUE, AUTHOR, OWNER, AMOUNT = 987654321, 7, 1234567, 424242, 5_000_000
N2048 = (1 << 2047) | 0x1234567  # an odd 2048-bit number: only its encoding matters here
CHECKS = bytes(range(32))
TID = bytes([0xC0 + i for i in range(32)])
JWT = "eyJhbGciOiJSUzI1NiJ9." + "A" * 1000 + ".c2ln"


def ix(i) -> dict:
    return {"program": str(i.program_id), "data": bytes(i.data).hex(),
            "accounts": [{"pubkey": str(a.pubkey), "signer": a.is_signer, "writable": a.is_writable} for a in i.accounts]}


def build() -> dict:
    job_own, job_wallet = pay.job_pda(REPO, ISSUE), pay.job_pda(REPO, ISSUE, K["funder"])
    return {
        "note": "Generated by scripts/settle_fixtures.py from src/knos/settle. Do not edit.",
        "programs": {"knos_oidc": str(oidc.OIDC_ID), "knos_pay": str(pay.PAY_ID)},
        "inputs": {**{k: str(v) for k, v in K.items()}, "repo_id": REPO, "issue": ISSUE, "author_id": AUTHOR, "owner_id": OWNER,
                   "amount": AMOUNT, "checks": CHECKS.hex(), "token_id": TID.hex(), "n2048": hex(N2048), "jwt": JWT,
                   "wf_repo": "drexthealpha/Knos", "wf_sha": "c" * 40},
        "addresses": {
            "auth": str(pay.auth_pda()), "vault(mint)": str(pay.vault_pda(K["mint"])), "faucet_mint": str(pay.faucet_mint()),
            "job(repo, issue) own": str(job_own), "job(repo, issue, funder)": str(job_wallet),
            "due(author, mint)": str(pay.due_pda(AUTHOR, K["mint"])), "rep(author)": str(pay.rep_pda(AUTHOR)),
            "rate(repo)": str(pay.rate_pda(REPO)), "ata(address, mint)": str(pay.ata(K["address"], K["mint"])),
            "fee_account(mint)": str(pay.ata(pay.FEE_OWNER, K["mint"])),
            "token(payer, token_id)": str(oidc.token_pda(K["payer"], TID)), "key(github, n2048)": str(oidc.key_pda(oidc.GITHUB, N2048)),
        },
        "audiences": {
            "fund merge": pay.fund_audience(ISSUE, AMOUNT),
            "fund tests": pay.fund_audience(ISSUE, AMOUNT, pay.TESTS, CHECKS, 14 * 86_400, 86_400),
            "pay merge": pay.pay_audience(REPO, ISSUE, AUTHOR, "a" * 40),
            "pay tests": pay.pay_audience(REPO, ISSUE, AUTHOR, "a" * 40, CHECKS, pay.TESTS),
            "veto": pay.veto_audience(REPO, ISSUE), "claim": pay.claim_audience(K["address"]),
            "rotate": oidc.rotate_audience(oidc.GITHUB, N2048),
        },
        "wf_repo_hash": pay.wf_repo_hash("drexthealpha/Knos").hex(),
        "fees": {str(a): pay.fee_of(a) for a in (0, 1, 50_000, 1_000_000, 2_000_000, 5_000_000, 500_000_000)},
        "instructions": {
            "oidc.write (first chunk)": ix(oidc.write_ixs(K["payer"], TID, JWT)[0]),
            "oidc.write (last chunk)": ix(oidc.write_ixs(K["payer"], TID, JWT)[-1]),
            "oidc.step": ix(oidc.step_ix(K["payer"], TID, oidc.key_pda(oidc.GITHUB, N2048), 8)),
            "oidc.close": ix(oidc.close_ix(K["payer"], TID)),
            "oidc.register_key": ix(oidc.register_key_ix(K["payer"], oidc.GITHUB, N2048)),
            "oidc.register_key (attested)": ix(oidc.register_key_ix(K["payer"], oidc.GITHUB, N2048, K["token_account"])),
            "oidc.key_params": ix(oidc.key_params_ix(K["payer"], oidc.GITHUB, N2048)),
            "pay.fund merge": ix(pay.fund_ix(K["funder"], K["funder_token"], K["mint"], REPO, ISSUE, AMOUNT, "drexthealpha/Knos", "c" * 40)),
            "pay.fund tests": ix(pay.fund_ix(K["funder"], K["funder_token"], K["mint"], REPO, ISSUE, AMOUNT, "drexthealpha/Knos", "c" * 40,
                                             mode=pay.TESTS, checks=CHECKS, work_s=7 * 86_400, review_s=86_400)),
            "pay.fund_with_token": ix(pay.fund_with_token_ix(K["relayer"], K["token_account"], REPO, ISSUE)),
            "pay.pay": ix(pay.pay_ix(K["relayer"], K["token_account"], job_wallet, AUTHOR, K["mint"], K["funder"])),
            "pay.settle": ix(pay.settle_ix(K["relayer"], job_wallet, AUTHOR, K["mint"], K["funder"])),
            "pay.veto (wallet)": ix(pay.veto_ix(K["funder"], job_wallet)),
            "pay.veto (token)": ix(pay.veto_ix(K["relayer"], job_own, K["token_account"])),
            "pay.refund": ix(pay.refund_ix(K["relayer"], job_wallet, K["mint"], K["funder_token"], K["funder"])),
            "pay.claim": ix(pay.claim_ix(K["relayer"], K["token_account"], AUTHOR, K["mint"], K["address"])),
            "pay.init_faucet": ix(pay.init_faucet_ix(K["payer"])),
            "create_ata": ix(pay.create_ata_ix(K["relayer"], K["address"], K["mint"])),
        },
        "layouts": {
            "job (256 bytes)": "0 state u8 (1 open, 2 proven) | 1 mode u8 | 2 kind u8 (0 wallet, 1 GitHub) | 8 repo_id u64 | 16 issue u64 | 24 amount u64 | "
                               "32 deadline i64 | 40 review i64 | 48 pay_after i64 | 56 author_id u64 | 64 funder_id u64 | 72 not_before i64 | 80 vetoes u32 | "
                               "88 funder[32] | 120 mint[32] | 152 checks[32] | 184 wf_repo_hash[32] | 216 wf_sha[40]",
            "due (48 bytes)": "0 amount u64 | 8 github user id u64 | 16 mint[32]",
            "rep (32 bytes)": "0 paid jobs u32 | 8 total paid u64 | 16 distinct repositories u32 | 24 last repository u64",
            "token (626 + jwt bytes)": "0 stage u8 (2 = verified) | 1 issuer u8 | 2 squarings done u8 | 3 limbs u8 | 4 jwt_len u16 | 6 payload_off u16 | "
                                       "8 payload_len u16 | 10 exp i64 | 18 key[32] | 50 payer[32] | 82 id[32] | 114 x[512] | 626 jwt",
            "key (8 + 8 * limbs bytes)": "0 ready u8 | 1 issuer u8 | 2 limbs u8 (64 or 128) | 3 bump u8 | 4 n0inv u32 | 8 n (LE limbs) | then r2 (LE limbs)",
        },
    }


if __name__ == "__main__":
    text = json.dumps(build(), indent=1) + "\n"
    if "--check" in sys.argv:
        sys.exit(0 if OUT.exists() and OUT.read_text(encoding="utf-8") == text else "sdk/settle/fixtures.json is stale: run python scripts/settle_fixtures.py")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT} ({len(text)} bytes)")
