"""Tamper benchmark: 21 test-weakening pull requests against a sample repo, judged three ways.

    python scripts/tamper_bench.py [--out docs/TAMPER.md]

"CI green" runs the PR's own CI test steps (the `run:` lines of its .github/workflows/ci.yml) in the PR's tree and
passes on exit 0, as a branch protection rule would. "Knos, tests" runs knos.judge.judge(base, pr, cfg) on the pytest
acceptance bundle (.knos/acceptance/1), the same function prove.yml's check job runs. "Knos, black box" runs it on the
black-box bundle (.knos/acceptance/2), whose check never loads the pull request's code. An attack "fools" a judge when
the judge passes it although slugify was not fixed.
"""

from __future__ import annotations

import argparse
import importlib.util
import os
import re
import shutil
import subprocess
import sys
import tempfile
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BENCH = ROOT / "tests" / "bench_tamper"
sys.path.insert(0, str(ROOT / "src"))

from knos import judge as prove  # noqa: E402


def _attacks():
    spec = importlib.util.spec_from_file_location("tamper_attacks", BENCH / "attacks.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def ci_green(pr: Path) -> bool:
    wf = pr / ".github" / "workflows" / "ci.yml"
    if not wf.is_file():
        return True   # no CI step: nothing fails
    runs = re.findall(r"^\s*-\s*run:\s*(.+)$", wf.read_text(encoding="utf-8"), re.M)
    for cmd in runs:
        cmd = re.sub(r"^python\b", lambda _: f'"{sys.executable}"', cmd.strip())
        env = {**os.environ, "PYTEST_DISABLE_PLUGIN_AUTOLOAD": "1", "PYTHONDONTWRITEBYTECODE": "1"}
        r = subprocess.run(cmd, shell=True, cwd=pr, env=env, capture_output=True, timeout=300)
        if r.returncode != 0:
            return False
    return True


def one(base: Path, tmp: Path, i: int, name: str, fn, cache: dict) -> dict:
    pr = tmp / f"pr{i}"
    shutil.copytree(base, pr)
    fn(pr)
    green = ci_green(pr)
    shutil.rmtree(pr / "__pycache__", ignore_errors=True)
    v = prove.judge(base, pr, {"issue": "1", "test_dirs": ["tests"]}, cache=cache)
    out = {"name": name, "ci": green, "knos": v["passed"], "why": "; ".join(v["reasons"]) or "-", "box": None}
    if BLACKBOX:
        b = prove.judge(base, pr, {"issue": "2", "test_dirs": ["tests"]}, cache=cache)
        out.update({"box": b["passed"], "box_why": "; ".join(b["reasons"]) or "-"})
    return out


BLACKBOX = os.name != "nt"   # the black-box check reaches the tree through a shell wrapper


def run() -> tuple[dict, list[dict]]:
    mod = _attacks()
    with tempfile.TemporaryDirectory(prefix="knos-tamper-") as t:
        tmp = Path(t)
        base = tmp / "base"
        shutil.copytree(BENCH / "sample", base, ignore=shutil.ignore_patterns("__pycache__"))
        jobs = [mod.CONTROL, *mod.ATTACKS]
        cache: dict = {}
        first = one(base, tmp, 0, *jobs[0], cache)   # the control also runs the base side once, for every PR
        with ThreadPoolExecutor(max_workers=8) as ex:
            got = [first, *ex.map(lambda a: one(base, tmp, a[0], *a[1], cache), list(enumerate(jobs))[1:])]
    for g in got:
        g["out_of_scope"] = g["name"] in mod.OUT_OF_SCOPE
    return got[0], got[1:]


def render(control: dict, rows: list[dict]) -> str:
    n = len(rows)
    ci = sum(r["ci"] for r in rows)
    kn = sum(r["knos"] for r in rows)
    bx = sum(bool(r["box"]) for r in rows)
    yes = lambda b: "n/a" if b is None else "PASS (fooled)" if b else "fail"  # noqa: E731
    out = ["# Tamper benchmark", "",
           "Generated by `python scripts/tamper_bench.py`; checked by tests/test_tamper_bench.py.", "",
           "A sample repo (tests/bench_tamper/sample) has one bug: `slugify` keeps punctuation. Each attack below is a",
           "pull request that does NOT fix the bug and instead weakens what judges it (tests/bench_tamper/attacks.py).",
           "Three judges see each one:", "",
           "- **CI green**: the PR's own CI test steps (its `.github/workflows/ci.yml`), run in the PR tree; pass on exit 0.",
           "- **Knos, tests**: `knos.judge.judge` on the funder's pytest bundle `.knos/acceptance/1/`: protected paths,",
           "  overlay of the base's tests and configuration, a random sentinel test and a failing canary, fail-to-pass,",
           "  pass-to-pass and test count. The code under test shares a process with the test runner.",
           "- **Knos, black box**: `knos.judge.judge` on the funder's black-box bundle `.knos/acceptance/2/`: the check",
           "  runs as the judge and never loads the pull request's code; it asks that code for answers through the",
           "  sandbox and compares them with its own reference on generated inputs.", "",
           f"**CI green fooled {ci}/{n}. Knos, tests: fooled {kn}/{n}. Knos, black box: fooled {bx}/{n}.**", "",
           f"Control (the honest fix): CI green {'passes' if control['ci'] else 'fails'}, "
           f"Knos, tests {'passes' if control['knos'] else 'fails'}, "
           f"Knos, black box {'passes' if control['box'] else 'n/a' if control['box'] is None else 'fails'}.", "",
           "| # | attack | CI green | Knos, tests | Knos, black box | Knos's reason (tests) |", "|---|---|---|---|---|---|"]
    for i, r in enumerate(rows, 1):
        why = r["why"].replace("|", "\\|")
        if len(why) > 120:
            why = why[:117] + "..."
        out.append(f"| {i} | {r['name']} | {yes(r['ci'])} | {yes(r['knos'])} | {yes(r['box'])} | {why} |")
    fooled = [r["name"] for r in rows if r["knos"]]
    out += ["", f"The {len(fooled)} that fool an in-process test run are limits of running tests at all, not bugs to patch:",
            "a stub that returns the expected constants passes any check made of fixed examples, and code that shares",
            "a process with the test runner can stop the acceptance bodies from running. The black-box check has",
            "neither weakness, because the pull request's code is never in the process that decides.",
            "For a bounty judged by in-process tests, the defence is the review window: the payment waits (24 hours by",
            "default) and the funder can veto it. The default mode avoids the question: it pays on a maintainer's merge.", ""]
    return "\n".join(out)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(ROOT / "docs" / "TAMPER.md"))
    a = ap.parse_args(argv)
    control, rows = run()
    text = render(control, rows)
    Path(a.out).write_text(text, encoding="utf-8")
    print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
