"""Write tests/fixtures/upgrade_gate.json: a build record as examples/upgrade_gate writes it in LiteSVM (the test build
of knos-oidc verified the token), with the address and the fields the Python client (knos.settle.v2.gate) derives and
reads. scripts/governance.test.mjs holds the Node script's derivation, reader and refusal to it. Nothing is random.

    python scripts/upgrade_gate_fixture.py            # write it
    python scripts/upgrade_gate_fixture.py --check    # exit 1 if the committed fixture is not what this writes
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tests"))

from knos.settle.v2 import gate  # noqa: E402

OUT = ROOT / "tests" / "fixtures" / "upgrade_gate.json"


def build() -> str:
    from test_upgrade_gate import COMMIT, ELF, HASH, PROGRAM, Gate
    c = Gate()
    assert c.record(c.token()), c.err
    at = gate.record_pda(PROGRAM, HASH)
    r = gate.read_record(c.data(at))
    want = {"note": "Generated by scripts/upgrade_gate_fixture.py. Do not edit.", "gate": str(gate.GATE_ID), "program": str(PROGRAM),
            "elf": ELF.hex(), "executable_hash": HASH.hex(), "audience": gate.audience(PROGRAM, HASH), "record": str(at),
            "record_data": c.data(at).hex(), "commit": COMMIT, "run_id": r.run_id, "time": r.time}
    assert (r.sha, r.executable, r.program) == (COMMIT, HASH, PROGRAM)
    return json.dumps(want, indent=1) + "\n"


if __name__ == "__main__":
    text = build()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            sys.exit("tests/fixtures/upgrade_gate.json is stale: run python scripts/upgrade_gate_fixture.py")
        sys.exit(0)
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT}")
