"""Write examples/x402_attested/fixtures.json: the chain the x402 "attested" example replays. A wallet funds a work order
(FundOrderWallet), a judge's token pays it to the seller (PayOrder), and, on a second chain, the same order is refunded
after its deadline instead. Everything is what the test build of knos_pay did in LiteSVM: the instruction bytes, the
Order account, the program's log lines. Nothing is random (the wallets come from seeds, the clock is fixed).

    python scripts/x402_fixture.py            # write it
    python scripts/x402_fixture.py --check    # exit 1 if the committed fixture is not what this writes
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tests"))

from solders.keypair import Keypair  # noqa: E402

from knos.settle.v2 import pay  # noqa: E402

OUT = ROOT / "examples" / "x402_attested" / "fixtures.json"
# the terms of the offer a seller copies (offer.devnet.json): canonical, as knos.terms.parse reads them, so an order
# funded with them can be judged and paid
TERMS = json.loads((ROOT / "examples" / "x402_attested" / "offer.devnet.json").read_text(encoding="utf-8"))["terms"].encode()
BUYER, SELLER = Keypair.from_seed(bytes([31]) * 32), Keypair.from_seed(bytes([32]) * 32)
SELLER_ID, ISSUE, AMOUNT, WORK, SEQ, PR = 5550123, 77, 20_000_000, 7 * 86_400, 0, 12


def run(refund: bool):
    from _order import HEAD, REPO, OrderChain
    from _pay2 import WF_REPO, WF_SHA
    c = OrderChain()
    c.svm.airdrop(BUYER.pubkey(), 10 ** 10)
    tok = c.token_account(BUYER.pubkey(), c.usdc)
    c.mint_to(c.usdc, tok, 100 * 10 ** 6)
    ix = pay.fund_order_wallet_ix(BUYER.pubkey(), tok, c.usdc, REPO, ISSUE, AMOUNT, WF_REPO, WF_SHA, TERMS, pay.MERGE, WORK, SEQ)
    assert c.send([ix], BUYER), c.err
    order, funded_at, funded = ix.accounts[1].pubkey, c.now(), c.said("knos3:")
    data = c.data(order)
    o = pay.read_order(data)
    if refund:
        c.warp(WORK + 1)
        assert c.refund(order), c.err
        return {"at": c.now(), "logs": c.said("knos3:")}
    c.warp(3600)
    assert c.pay(order, [(SELLER_ID, 10_000, SELLER.pubkey())], pr=PR), c.err
    paid = {"at": c.now(), "logs": c.said("knos3:"), "received": c.balance(pay.ata(SELLER.pubkey(), c.usdc))}
    return {
        "note": "Generated by scripts/x402_fixture.py. Do not edit.", "program": str(pay.PAY_ID), "mint": str(c.usdc), "decimals": 6,
        "buyer": str(BUYER.pubkey()), "buyer_token": str(tok), "seller": {"github_id": SELLER_ID, "wallet": str(SELLER.pubkey())},
        "repo_id": REPO, "issue": ISSUE, "amount": AMOUNT, "fee": o.fee, "mode": pay.MERGE, "work_s": WORK, "seq": SEQ, "pr": PR, "head": HEAD,
        "terms": TERMS.decode(), "terms_hash": pay.terms_hash(TERMS).hex(), "wf_repo": WF_REPO, "wf_sha": WF_SHA,
        "fund": {"at": funded_at, "data": bytes(ix.data).hex(), "accounts": [[str(a.pubkey), a.is_signer, a.is_writable] for a in ix.accounts], "logs": funded},
        "order": {"address": str(order), "ov": str(pay.ov_pda(order)), "data": data.hex(), "deadline": o.deadline},
        "paid": paid,
    }


def build() -> str:
    want = run(False)
    want["refunded"] = run(True)
    return json.dumps(want, indent=1) + "\n"


if __name__ == "__main__":
    text = build()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            sys.exit("examples/x402_attested/fixtures.json is stale: run python scripts/x402_fixture.py")
        sys.exit(0)
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT}")
